// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: RequestNewOrder.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// PB_OFFSET = 100000, is the offset added for each MNM field id
public struct RtiRequestNewOrder {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// PB_OFFSET + MNM_TEMPLATE_ID
  public var templateID: Int32 {
    get {return _storage._templateID ?? 0}
    set {_uniqueStorage()._templateID = newValue}
  }
  /// Returns true if `templateID` has been explicitly set.
  public var hasTemplateID: Bool {return _storage._templateID != nil}
  /// Clears the value of `templateID`. Subsequent reads from it will return its default value.
  public mutating func clearTemplateID() {_uniqueStorage()._templateID = nil}

  /// PB_OFFSET + MNM_USER_MSG
  public var userMsg: [String] {
    get {return _storage._userMsg}
    set {_uniqueStorage()._userMsg = newValue}
  }

  /// PB_OFFSET + MNM_FCM_ID
  public var fcmID: String {
    get {return _storage._fcmID ?? String()}
    set {_uniqueStorage()._fcmID = newValue}
  }
  /// Returns true if `fcmID` has been explicitly set.
  public var hasFcmID: Bool {return _storage._fcmID != nil}
  /// Clears the value of `fcmID`. Subsequent reads from it will return its default value.
  public mutating func clearFcmID() {_uniqueStorage()._fcmID = nil}

  /// PB_OFFSET + MNM_IB_ID
  public var ibID: String {
    get {return _storage._ibID ?? String()}
    set {_uniqueStorage()._ibID = newValue}
  }
  /// Returns true if `ibID` has been explicitly set.
  public var hasIbID: Bool {return _storage._ibID != nil}
  /// Clears the value of `ibID`. Subsequent reads from it will return its default value.
  public mutating func clearIbID() {_uniqueStorage()._ibID = nil}

  /// PB_OFFSET + MNM_ACCOUNT_ID
  public var accountID: String {
    get {return _storage._accountID ?? String()}
    set {_uniqueStorage()._accountID = newValue}
  }
  /// Returns true if `accountID` has been explicitly set.
  public var hasAccountID: Bool {return _storage._accountID != nil}
  /// Clears the value of `accountID`. Subsequent reads from it will return its default value.
  public mutating func clearAccountID() {_uniqueStorage()._accountID = nil}

  /// PB_OFFSET + MNM_SYMBOL
  public var symbol: String {
    get {return _storage._symbol ?? String()}
    set {_uniqueStorage()._symbol = newValue}
  }
  /// Returns true if `symbol` has been explicitly set.
  public var hasSymbol: Bool {return _storage._symbol != nil}
  /// Clears the value of `symbol`. Subsequent reads from it will return its default value.
  public mutating func clearSymbol() {_uniqueStorage()._symbol = nil}

  /// PB_OFFSET + MNM_EXCHANGE
  public var exchange: String {
    get {return _storage._exchange ?? String()}
    set {_uniqueStorage()._exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {return _storage._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {_uniqueStorage()._exchange = nil}

  /// PB_OFFSET + MNM_QUAN_TO_FILL
  public var quantity: Int32 {
    get {return _storage._quantity ?? 0}
    set {_uniqueStorage()._quantity = newValue}
  }
  /// Returns true if `quantity` has been explicitly set.
  public var hasQuantity: Bool {return _storage._quantity != nil}
  /// Clears the value of `quantity`. Subsequent reads from it will return its default value.
  public mutating func clearQuantity() {_uniqueStorage()._quantity = nil}

  /// PB_OFFSET + MNM_PRICE_TO_FILL
  public var price: Double {
    get {return _storage._price ?? 0}
    set {_uniqueStorage()._price = newValue}
  }
  /// Returns true if `price` has been explicitly set.
  public var hasPrice: Bool {return _storage._price != nil}
  /// Clears the value of `price`. Subsequent reads from it will return its default value.
  public mutating func clearPrice() {_uniqueStorage()._price = nil}

  /// PB_OFFSET + MNM_TRIGGER_PRICE
  public var triggerPrice: Double {
    get {return _storage._triggerPrice ?? 0}
    set {_uniqueStorage()._triggerPrice = newValue}
  }
  /// Returns true if `triggerPrice` has been explicitly set.
  public var hasTriggerPrice: Bool {return _storage._triggerPrice != nil}
  /// Clears the value of `triggerPrice`. Subsequent reads from it will return its default value.
  public mutating func clearTriggerPrice() {_uniqueStorage()._triggerPrice = nil}

  /// PB_OFFSET + MNM_TRANSACTION_TYPE
  public var transactionType: RtiRequestNewOrder.TransactionType {
    get {return _storage._transactionType ?? .buy}
    set {_uniqueStorage()._transactionType = newValue}
  }
  /// Returns true if `transactionType` has been explicitly set.
  public var hasTransactionType: Bool {return _storage._transactionType != nil}
  /// Clears the value of `transactionType`. Subsequent reads from it will return its default value.
  public mutating func clearTransactionType() {_uniqueStorage()._transactionType = nil}

  /// PB_OFFSET + MNM_DURATION
  public var duration: RtiRequestNewOrder.Duration {
    get {return _storage._duration ?? .day}
    set {_uniqueStorage()._duration = newValue}
  }
  /// Returns true if `duration` has been explicitly set.
  public var hasDuration: Bool {return _storage._duration != nil}
  /// Clears the value of `duration`. Subsequent reads from it will return its default value.
  public mutating func clearDuration() {_uniqueStorage()._duration = nil}

  /// PB_OFFSET + MNM_PRICE_TYPE
  public var priceType: RtiRequestNewOrder.PriceType {
    get {return _storage._priceType ?? .limit}
    set {_uniqueStorage()._priceType = newValue}
  }
  /// Returns true if `priceType` has been explicitly set.
  public var hasPriceType: Bool {return _storage._priceType != nil}
  /// Clears the value of `priceType`. Subsequent reads from it will return its default value.
  public mutating func clearPriceType() {_uniqueStorage()._priceType = nil}

  /// PB_OFFSET + MNM_TRADE_ROUTE	
  public var tradeRoute: String {
    get {return _storage._tradeRoute ?? String()}
    set {_uniqueStorage()._tradeRoute = newValue}
  }
  /// Returns true if `tradeRoute` has been explicitly set.
  public var hasTradeRoute: Bool {return _storage._tradeRoute != nil}
  /// Clears the value of `tradeRoute`. Subsequent reads from it will return its default value.
  public mutating func clearTradeRoute() {_uniqueStorage()._tradeRoute = nil}

  /// PB_OFFSET + MNM_MANUAL_OR_AUTO
  public var manualOrAuto: RtiRequestNewOrder.OrderPlacement {
    get {return _storage._manualOrAuto ?? .manual}
    set {_uniqueStorage()._manualOrAuto = newValue}
  }
  /// Returns true if `manualOrAuto` has been explicitly set.
  public var hasManualOrAuto: Bool {return _storage._manualOrAuto != nil}
  /// Clears the value of `manualOrAuto`. Subsequent reads from it will return its default value.
  public mutating func clearManualOrAuto() {_uniqueStorage()._manualOrAuto = nil}

  /// PB_OFFSET + MNM_TRIGGER_SYMBOL
  public var ifTouchedSymbol: String {
    get {return _storage._ifTouchedSymbol ?? String()}
    set {_uniqueStorage()._ifTouchedSymbol = newValue}
  }
  /// Returns true if `ifTouchedSymbol` has been explicitly set.
  public var hasIfTouchedSymbol: Bool {return _storage._ifTouchedSymbol != nil}
  /// Clears the value of `ifTouchedSymbol`. Subsequent reads from it will return its default value.
  public mutating func clearIfTouchedSymbol() {_uniqueStorage()._ifTouchedSymbol = nil}

  /// PB_OFFSET + MNM_TRIGGER_EXCHANGE
  public var ifTouchedExchange: String {
    get {return _storage._ifTouchedExchange ?? String()}
    set {_uniqueStorage()._ifTouchedExchange = newValue}
  }
  /// Returns true if `ifTouchedExchange` has been explicitly set.
  public var hasIfTouchedExchange: Bool {return _storage._ifTouchedExchange != nil}
  /// Clears the value of `ifTouchedExchange`. Subsequent reads from it will return its default value.
  public mutating func clearIfTouchedExchange() {_uniqueStorage()._ifTouchedExchange = nil}

  /// PB_OFFSET + MNM_TRIGGER_CONDITION
  public var ifTouchedCondition: RtiRequestNewOrder.Condition {
    get {return _storage._ifTouchedCondition ?? .equalTo}
    set {_uniqueStorage()._ifTouchedCondition = newValue}
  }
  /// Returns true if `ifTouchedCondition` has been explicitly set.
  public var hasIfTouchedCondition: Bool {return _storage._ifTouchedCondition != nil}
  /// Clears the value of `ifTouchedCondition`. Subsequent reads from it will return its default value.
  public mutating func clearIfTouchedCondition() {_uniqueStorage()._ifTouchedCondition = nil}

  /// PB_OFFSET + MNM_COMPARE_FIELD
  public var ifTouchedPriceField: RtiRequestNewOrder.PriceField {
    get {return _storage._ifTouchedPriceField ?? .bidPrice}
    set {_uniqueStorage()._ifTouchedPriceField = newValue}
  }
  /// Returns true if `ifTouchedPriceField` has been explicitly set.
  public var hasIfTouchedPriceField: Bool {return _storage._ifTouchedPriceField != nil}
  /// Clears the value of `ifTouchedPriceField`. Subsequent reads from it will return its default value.
  public mutating func clearIfTouchedPriceField() {_uniqueStorage()._ifTouchedPriceField = nil}

  /// PB_OFFSET + MNM_IF_TOUCHED_PRICE
  public var ifTouchedPrice: Double {
    get {return _storage._ifTouchedPrice ?? 0}
    set {_uniqueStorage()._ifTouchedPrice = newValue}
  }
  /// Returns true if `ifTouchedPrice` has been explicitly set.
  public var hasIfTouchedPrice: Bool {return _storage._ifTouchedPrice != nil}
  /// Clears the value of `ifTouchedPrice`. Subsequent reads from it will return its default value.
  public mutating func clearIfTouchedPrice() {_uniqueStorage()._ifTouchedPrice = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum TransactionType: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case buy // = 1
    case sell // = 2

    public init() {
      self = .buy
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .buy
      case 2: self = .sell
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .buy: return 1
      case .sell: return 2
      }
    }

  }

  public enum OrderPlacement: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case manual // = 1
    case auto // = 2

    public init() {
      self = .manual
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .manual
      case 2: self = .auto
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .manual: return 1
      case .auto: return 2
      }
    }

  }

  public enum Duration: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case day // = 1
    case gtc // = 2
    case ioc // = 3
    case fok // = 4

    public init() {
      self = .day
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .day
      case 2: self = .gtc
      case 3: self = .ioc
      case 4: self = .fok
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .day: return 1
      case .gtc: return 2
      case .ioc: return 3
      case .fok: return 4
      }
    }

  }

  public enum PriceType: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case limit // = 1
    case market // = 2
    case stopLimit // = 3
    case stopMarket // = 4
    case marketIfTouched // = 5
    case limitIfTouched // = 6

    public init() {
      self = .limit
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .limit
      case 2: self = .market
      case 3: self = .stopLimit
      case 4: self = .stopMarket
      case 5: self = .marketIfTouched
      case 6: self = .limitIfTouched
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .limit: return 1
      case .market: return 2
      case .stopLimit: return 3
      case .stopMarket: return 4
      case .marketIfTouched: return 5
      case .limitIfTouched: return 6
      }
    }

  }

  public enum PriceField: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case bidPrice // = 1
    case offerPrice // = 2
    case tradePrice // = 3
    case leanPrice // = 4

    public init() {
      self = .bidPrice
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .bidPrice
      case 2: self = .offerPrice
      case 3: self = .tradePrice
      case 4: self = .leanPrice
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .bidPrice: return 1
      case .offerPrice: return 2
      case .tradePrice: return 3
      case .leanPrice: return 4
      }
    }

  }

  public enum Condition: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case equalTo // = 1
    case notEqualTo // = 2
    case greaterThan // = 3
    case greaterThanEqualTo // = 4
    case lesserThan // = 5
    case lesserThanEqualTo // = 6

    public init() {
      self = .equalTo
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .equalTo
      case 2: self = .notEqualTo
      case 3: self = .greaterThan
      case 4: self = .greaterThanEqualTo
      case 5: self = .lesserThan
      case 6: self = .lesserThanEqualTo
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .equalTo: return 1
      case .notEqualTo: return 2
      case .greaterThan: return 3
      case .greaterThanEqualTo: return 4
      case .lesserThan: return 5
      case .lesserThanEqualTo: return 6
      }
    }

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

#if swift(>=4.2)

extension RtiRequestNewOrder.TransactionType: CaseIterable {
  // Support synthesized by the compiler.
}

extension RtiRequestNewOrder.OrderPlacement: CaseIterable {
  // Support synthesized by the compiler.
}

extension RtiRequestNewOrder.Duration: CaseIterable {
  // Support synthesized by the compiler.
}

extension RtiRequestNewOrder.PriceType: CaseIterable {
  // Support synthesized by the compiler.
}

extension RtiRequestNewOrder.PriceField: CaseIterable {
  // Support synthesized by the compiler.
}

extension RtiRequestNewOrder.Condition: CaseIterable {
  // Support synthesized by the compiler.
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rti"

extension RtiRequestNewOrder: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestNewOrder"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    154467: .standard(proto: "template_id"),
    132760: .standard(proto: "user_msg"),
    154013: .standard(proto: "fcm_id"),
    154014: .standard(proto: "ib_id"),
    154008: .standard(proto: "account_id"),
    110100: .same(proto: "symbol"),
    110101: .same(proto: "exchange"),
    112004: .same(proto: "quantity"),
    110306: .same(proto: "price"),
    149247: .standard(proto: "trigger_price"),
    112003: .standard(proto: "transaction_type"),
    112005: .same(proto: "duration"),
    112008: .standard(proto: "price_type"),
    112016: .standard(proto: "trade_route"),
    154710: .standard(proto: "manual_or_auto"),
    154451: .standard(proto: "if_touched_symbol"),
    154452: .standard(proto: "if_touched_exchange"),
    154453: .standard(proto: "if_touched_condition"),
    154454: .standard(proto: "if_touched_price_field"),
    153632: .standard(proto: "if_touched_price"),
  ]

  fileprivate class _StorageClass {
    var _templateID: Int32? = nil
    var _userMsg: [String] = []
    var _fcmID: String? = nil
    var _ibID: String? = nil
    var _accountID: String? = nil
    var _symbol: String? = nil
    var _exchange: String? = nil
    var _quantity: Int32? = nil
    var _price: Double? = nil
    var _triggerPrice: Double? = nil
    var _transactionType: RtiRequestNewOrder.TransactionType? = nil
    var _duration: RtiRequestNewOrder.Duration? = nil
    var _priceType: RtiRequestNewOrder.PriceType? = nil
    var _tradeRoute: String? = nil
    var _manualOrAuto: RtiRequestNewOrder.OrderPlacement? = nil
    var _ifTouchedSymbol: String? = nil
    var _ifTouchedExchange: String? = nil
    var _ifTouchedCondition: RtiRequestNewOrder.Condition? = nil
    var _ifTouchedPriceField: RtiRequestNewOrder.PriceField? = nil
    var _ifTouchedPrice: Double? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _templateID = source._templateID
      _userMsg = source._userMsg
      _fcmID = source._fcmID
      _ibID = source._ibID
      _accountID = source._accountID
      _symbol = source._symbol
      _exchange = source._exchange
      _quantity = source._quantity
      _price = source._price
      _triggerPrice = source._triggerPrice
      _transactionType = source._transactionType
      _duration = source._duration
      _priceType = source._priceType
      _tradeRoute = source._tradeRoute
      _manualOrAuto = source._manualOrAuto
      _ifTouchedSymbol = source._ifTouchedSymbol
      _ifTouchedExchange = source._ifTouchedExchange
      _ifTouchedCondition = source._ifTouchedCondition
      _ifTouchedPriceField = source._ifTouchedPriceField
      _ifTouchedPrice = source._ifTouchedPrice
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._templateID == nil {return false}
      return true
    }
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 110100: try decoder.decodeSingularStringField(value: &_storage._symbol)
        case 110101: try decoder.decodeSingularStringField(value: &_storage._exchange)
        case 110306: try decoder.decodeSingularDoubleField(value: &_storage._price)
        case 112003: try decoder.decodeSingularEnumField(value: &_storage._transactionType)
        case 112004: try decoder.decodeSingularInt32Field(value: &_storage._quantity)
        case 112005: try decoder.decodeSingularEnumField(value: &_storage._duration)
        case 112008: try decoder.decodeSingularEnumField(value: &_storage._priceType)
        case 112016: try decoder.decodeSingularStringField(value: &_storage._tradeRoute)
        case 132760: try decoder.decodeRepeatedStringField(value: &_storage._userMsg)
        case 149247: try decoder.decodeSingularDoubleField(value: &_storage._triggerPrice)
        case 153632: try decoder.decodeSingularDoubleField(value: &_storage._ifTouchedPrice)
        case 154008: try decoder.decodeSingularStringField(value: &_storage._accountID)
        case 154013: try decoder.decodeSingularStringField(value: &_storage._fcmID)
        case 154014: try decoder.decodeSingularStringField(value: &_storage._ibID)
        case 154451: try decoder.decodeSingularStringField(value: &_storage._ifTouchedSymbol)
        case 154452: try decoder.decodeSingularStringField(value: &_storage._ifTouchedExchange)
        case 154453: try decoder.decodeSingularEnumField(value: &_storage._ifTouchedCondition)
        case 154454: try decoder.decodeSingularEnumField(value: &_storage._ifTouchedPriceField)
        case 154467: try decoder.decodeSingularInt32Field(value: &_storage._templateID)
        case 154710: try decoder.decodeSingularEnumField(value: &_storage._manualOrAuto)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._symbol {
        try visitor.visitSingularStringField(value: v, fieldNumber: 110100)
      }
      if let v = _storage._exchange {
        try visitor.visitSingularStringField(value: v, fieldNumber: 110101)
      }
      if let v = _storage._price {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 110306)
      }
      if let v = _storage._transactionType {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 112003)
      }
      if let v = _storage._quantity {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 112004)
      }
      if let v = _storage._duration {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 112005)
      }
      if let v = _storage._priceType {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 112008)
      }
      if let v = _storage._tradeRoute {
        try visitor.visitSingularStringField(value: v, fieldNumber: 112016)
      }
      if !_storage._userMsg.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._userMsg, fieldNumber: 132760)
      }
      if let v = _storage._triggerPrice {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 149247)
      }
      if let v = _storage._ifTouchedPrice {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 153632)
      }
      if let v = _storage._accountID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 154008)
      }
      if let v = _storage._fcmID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 154013)
      }
      if let v = _storage._ibID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 154014)
      }
      if let v = _storage._ifTouchedSymbol {
        try visitor.visitSingularStringField(value: v, fieldNumber: 154451)
      }
      if let v = _storage._ifTouchedExchange {
        try visitor.visitSingularStringField(value: v, fieldNumber: 154452)
      }
      if let v = _storage._ifTouchedCondition {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 154453)
      }
      if let v = _storage._ifTouchedPriceField {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 154454)
      }
      if let v = _storage._templateID {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 154467)
      }
      if let v = _storage._manualOrAuto {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 154710)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RtiRequestNewOrder, rhs: RtiRequestNewOrder) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._templateID != rhs_storage._templateID {return false}
        if _storage._userMsg != rhs_storage._userMsg {return false}
        if _storage._fcmID != rhs_storage._fcmID {return false}
        if _storage._ibID != rhs_storage._ibID {return false}
        if _storage._accountID != rhs_storage._accountID {return false}
        if _storage._symbol != rhs_storage._symbol {return false}
        if _storage._exchange != rhs_storage._exchange {return false}
        if _storage._quantity != rhs_storage._quantity {return false}
        if _storage._price != rhs_storage._price {return false}
        if _storage._triggerPrice != rhs_storage._triggerPrice {return false}
        if _storage._transactionType != rhs_storage._transactionType {return false}
        if _storage._duration != rhs_storage._duration {return false}
        if _storage._priceType != rhs_storage._priceType {return false}
        if _storage._tradeRoute != rhs_storage._tradeRoute {return false}
        if _storage._manualOrAuto != rhs_storage._manualOrAuto {return false}
        if _storage._ifTouchedSymbol != rhs_storage._ifTouchedSymbol {return false}
        if _storage._ifTouchedExchange != rhs_storage._ifTouchedExchange {return false}
        if _storage._ifTouchedCondition != rhs_storage._ifTouchedCondition {return false}
        if _storage._ifTouchedPriceField != rhs_storage._ifTouchedPriceField {return false}
        if _storage._ifTouchedPrice != rhs_storage._ifTouchedPrice {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RtiRequestNewOrder.TransactionType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "BUY"),
    2: .same(proto: "SELL"),
  ]
}

extension RtiRequestNewOrder.OrderPlacement: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "MANUAL"),
    2: .same(proto: "AUTO"),
  ]
}

extension RtiRequestNewOrder.Duration: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "DAY"),
    2: .same(proto: "GTC"),
    3: .same(proto: "IOC"),
    4: .same(proto: "FOK"),
  ]
}

extension RtiRequestNewOrder.PriceType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "LIMIT"),
    2: .same(proto: "MARKET"),
    3: .same(proto: "STOP_LIMIT"),
    4: .same(proto: "STOP_MARKET"),
    5: .same(proto: "MARKET_IF_TOUCHED"),
    6: .same(proto: "LIMIT_IF_TOUCHED"),
  ]
}

extension RtiRequestNewOrder.PriceField: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "BID_PRICE"),
    2: .same(proto: "OFFER_PRICE"),
    3: .same(proto: "TRADE_PRICE"),
    4: .same(proto: "LEAN_PRICE"),
  ]
}

extension RtiRequestNewOrder.Condition: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "EQUAL_TO"),
    2: .same(proto: "NOT_EQUAL_TO"),
    3: .same(proto: "GREATER_THAN"),
    4: .same(proto: "GREATER_THAN_EQUAL_TO"),
    5: .same(proto: "LESSER_THAN"),
    6: .same(proto: "LESSER_THAN_EQUAL_TO"),
  ]
}
