// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: RequestCancelOrder.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// PB_OFFSET = 100000, is the offset added for each MNM field id
public struct RtiRequestCancelOrder {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// PB_OFFSET + MNM_TEMPLATE_ID
  public var templateID: Int32 {
    get {return _templateID ?? 0}
    set {_templateID = newValue}
  }
  /// Returns true if `templateID` has been explicitly set.
  public var hasTemplateID: Bool {return self._templateID != nil}
  /// Clears the value of `templateID`. Subsequent reads from it will return its default value.
  public mutating func clearTemplateID() {self._templateID = nil}

  /// PB_OFFSET + MNM_USER_MSG
  public var userMsg: [String] = []

  /// PB_OFFSET + MNM_FCM_ID
  public var fcmID: String {
    get {return _fcmID ?? String()}
    set {_fcmID = newValue}
  }
  /// Returns true if `fcmID` has been explicitly set.
  public var hasFcmID: Bool {return self._fcmID != nil}
  /// Clears the value of `fcmID`. Subsequent reads from it will return its default value.
  public mutating func clearFcmID() {self._fcmID = nil}

  /// PB_OFFSET + MNM_IB_ID
  public var ibID: String {
    get {return _ibID ?? String()}
    set {_ibID = newValue}
  }
  /// Returns true if `ibID` has been explicitly set.
  public var hasIbID: Bool {return self._ibID != nil}
  /// Clears the value of `ibID`. Subsequent reads from it will return its default value.
  public mutating func clearIbID() {self._ibID = nil}

  /// PB_OFFSET + MNM_ACCOUNT_ID
  public var accountID: String {
    get {return _accountID ?? String()}
    set {_accountID = newValue}
  }
  /// Returns true if `accountID` has been explicitly set.
  public var hasAccountID: Bool {return self._accountID != nil}
  /// Clears the value of `accountID`. Subsequent reads from it will return its default value.
  public mutating func clearAccountID() {self._accountID = nil}

  /// PB_OFFSET + MNM_BASKET_ID
  public var basketID: String {
    get {return _basketID ?? String()}
    set {_basketID = newValue}
  }
  /// Returns true if `basketID` has been explicitly set.
  public var hasBasketID: Bool {return self._basketID != nil}
  /// Clears the value of `basketID`. Subsequent reads from it will return its default value.
  public mutating func clearBasketID() {self._basketID = nil}

  /// PB_OFFSET + MNM_MANUAL_OR_AUTO
  public var manualOrAuto: RtiRequestCancelOrder.OrderPlacement {
    get {return _manualOrAuto ?? .manual}
    set {_manualOrAuto = newValue}
  }
  /// Returns true if `manualOrAuto` has been explicitly set.
  public var hasManualOrAuto: Bool {return self._manualOrAuto != nil}
  /// Clears the value of `manualOrAuto`. Subsequent reads from it will return its default value.
  public mutating func clearManualOrAuto() {self._manualOrAuto = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OrderPlacement: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case manual // = 1
    case auto // = 2

    public init() {
      self = .manual
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .manual
      case 2: self = .auto
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .manual: return 1
      case .auto: return 2
      }
    }

  }

  public init() {}

  fileprivate var _templateID: Int32? = nil
  fileprivate var _fcmID: String? = nil
  fileprivate var _ibID: String? = nil
  fileprivate var _accountID: String? = nil
  fileprivate var _basketID: String? = nil
  fileprivate var _manualOrAuto: RtiRequestCancelOrder.OrderPlacement? = nil
}

#if swift(>=4.2)

extension RtiRequestCancelOrder.OrderPlacement: CaseIterable {
  // Support synthesized by the compiler.
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rti"

extension RtiRequestCancelOrder: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestCancelOrder"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    154467: .standard(proto: "template_id"),
    132760: .standard(proto: "user_msg"),
    154013: .standard(proto: "fcm_id"),
    154014: .standard(proto: "ib_id"),
    154008: .standard(proto: "account_id"),
    110300: .standard(proto: "basket_id"),
    154710: .standard(proto: "manual_or_auto"),
  ]

  public var isInitialized: Bool {
    if self._templateID == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 110300: try decoder.decodeSingularStringField(value: &self._basketID)
      case 132760: try decoder.decodeRepeatedStringField(value: &self.userMsg)
      case 154008: try decoder.decodeSingularStringField(value: &self._accountID)
      case 154013: try decoder.decodeSingularStringField(value: &self._fcmID)
      case 154014: try decoder.decodeSingularStringField(value: &self._ibID)
      case 154467: try decoder.decodeSingularInt32Field(value: &self._templateID)
      case 154710: try decoder.decodeSingularEnumField(value: &self._manualOrAuto)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._basketID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 110300)
    }
    if !self.userMsg.isEmpty {
      try visitor.visitRepeatedStringField(value: self.userMsg, fieldNumber: 132760)
    }
    if let v = self._accountID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 154008)
    }
    if let v = self._fcmID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 154013)
    }
    if let v = self._ibID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 154014)
    }
    if let v = self._templateID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 154467)
    }
    if let v = self._manualOrAuto {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 154710)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RtiRequestCancelOrder, rhs: RtiRequestCancelOrder) -> Bool {
    if lhs._templateID != rhs._templateID {return false}
    if lhs.userMsg != rhs.userMsg {return false}
    if lhs._fcmID != rhs._fcmID {return false}
    if lhs._ibID != rhs._ibID {return false}
    if lhs._accountID != rhs._accountID {return false}
    if lhs._basketID != rhs._basketID {return false}
    if lhs._manualOrAuto != rhs._manualOrAuto {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RtiRequestCancelOrder.OrderPlacement: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "MANUAL"),
    2: .same(proto: "AUTO"),
  ]
}
