// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: RithmicOrderNotification.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// PB_OFFSET = 100000, is the offset added for each MNM field id
public struct RtiRithmicOrderNotification {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// PB_OFFSET + MNM_TEMPLATE_ID
  public var templateID: Int32 {
    get {return _storage._templateID ?? 0}
    set {_uniqueStorage()._templateID = newValue}
  }
  /// Returns true if `templateID` has been explicitly set.
  public var hasTemplateID: Bool {return _storage._templateID != nil}
  /// Clears the value of `templateID`. Subsequent reads from it will return its default value.
  public mutating func clearTemplateID() {_uniqueStorage()._templateID = nil}

  /// PB_OFFSET + MNM_NOTIFICATION_TYPE
  public var notifyType: RtiRithmicOrderNotification.NotifyType {
    get {return _storage._notifyType ?? .orderRcvdFromClnt}
    set {_uniqueStorage()._notifyType = newValue}
  }
  /// Returns true if `notifyType` has been explicitly set.
  public var hasNotifyType: Bool {return _storage._notifyType != nil}
  /// Clears the value of `notifyType`. Subsequent reads from it will return its default value.
  public mutating func clearNotifyType() {_uniqueStorage()._notifyType = nil}

  /// PB_OFFSET + MNM_UPDATE_TYPE               
  public var isSnapshot: Bool {
    get {return _storage._isSnapshot ?? false}
    set {_uniqueStorage()._isSnapshot = newValue}
  }
  /// Returns true if `isSnapshot` has been explicitly set.
  public var hasIsSnapshot: Bool {return _storage._isSnapshot != nil}
  /// Clears the value of `isSnapshot`. Subsequent reads from it will return its default value.
  public mutating func clearIsSnapshot() {_uniqueStorage()._isSnapshot = nil}

  /// PB_OFFSET + MNM_STATUS
  public var status: String {
    get {return _storage._status ?? String()}
    set {_uniqueStorage()._status = newValue}
  }
  /// Returns true if `status` has been explicitly set.
  public var hasStatus: Bool {return _storage._status != nil}
  /// Clears the value of `status`. Subsequent reads from it will return its default value.
  public mutating func clearStatus() {_uniqueStorage()._status = nil}

  /// PB_OFFSET + MNM_BASKET_ID
  public var basketID: String {
    get {return _storage._basketID ?? String()}
    set {_uniqueStorage()._basketID = newValue}
  }
  /// Returns true if `basketID` has been explicitly set.
  public var hasBasketID: Bool {return _storage._basketID != nil}
  /// Clears the value of `basketID`. Subsequent reads from it will return its default value.
  public mutating func clearBasketID() {_uniqueStorage()._basketID = nil}

  /// PB_OFFSET + MNM_ORIGINAL_BASKET_ID
  public var originalBasketID: String {
    get {return _storage._originalBasketID ?? String()}
    set {_uniqueStorage()._originalBasketID = newValue}
  }
  /// Returns true if `originalBasketID` has been explicitly set.
  public var hasOriginalBasketID: Bool {return _storage._originalBasketID != nil}
  /// Clears the value of `originalBasketID`. Subsequent reads from it will return its default value.
  public mutating func clearOriginalBasketID() {_uniqueStorage()._originalBasketID = nil}

  /// PB_OFFSET + MNM_FCM_ID
  public var fcmID: String {
    get {return _storage._fcmID ?? String()}
    set {_uniqueStorage()._fcmID = newValue}
  }
  /// Returns true if `fcmID` has been explicitly set.
  public var hasFcmID: Bool {return _storage._fcmID != nil}
  /// Clears the value of `fcmID`. Subsequent reads from it will return its default value.
  public mutating func clearFcmID() {_uniqueStorage()._fcmID = nil}

  /// PB_OFFSET + MNM_IB_ID
  public var ibID: String {
    get {return _storage._ibID ?? String()}
    set {_uniqueStorage()._ibID = newValue}
  }
  /// Returns true if `ibID` has been explicitly set.
  public var hasIbID: Bool {return _storage._ibID != nil}
  /// Clears the value of `ibID`. Subsequent reads from it will return its default value.
  public mutating func clearIbID() {_uniqueStorage()._ibID = nil}

  /// PB_OFFSET + MNM_USER_ID
  public var userID: String {
    get {return _storage._userID ?? String()}
    set {_uniqueStorage()._userID = newValue}
  }
  /// Returns true if `userID` has been explicitly set.
  public var hasUserID: Bool {return _storage._userID != nil}
  /// Clears the value of `userID`. Subsequent reads from it will return its default value.
  public mutating func clearUserID() {_uniqueStorage()._userID = nil}

  /// PB_OFFSET + MNM_ACCOUNT_ID
  public var accountID: String {
    get {return _storage._accountID ?? String()}
    set {_uniqueStorage()._accountID = newValue}
  }
  /// Returns true if `accountID` has been explicitly set.
  public var hasAccountID: Bool {return _storage._accountID != nil}
  /// Clears the value of `accountID`. Subsequent reads from it will return its default value.
  public mutating func clearAccountID() {_uniqueStorage()._accountID = nil}

  /// PB_OFFSET + MNM_SYMBOL
  public var symbol: String {
    get {return _storage._symbol ?? String()}
    set {_uniqueStorage()._symbol = newValue}
  }
  /// Returns true if `symbol` has been explicitly set.
  public var hasSymbol: Bool {return _storage._symbol != nil}
  /// Clears the value of `symbol`. Subsequent reads from it will return its default value.
  public mutating func clearSymbol() {_uniqueStorage()._symbol = nil}

  /// PB_OFFSET + MNM_EXCHANGE
  public var exchange: String {
    get {return _storage._exchange ?? String()}
    set {_uniqueStorage()._exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {return _storage._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {_uniqueStorage()._exchange = nil}

  /// PB_OFFSET + MNM_TRADE_EXCHANGE
  public var tradeExchange: String {
    get {return _storage._tradeExchange ?? String()}
    set {_uniqueStorage()._tradeExchange = newValue}
  }
  /// Returns true if `tradeExchange` has been explicitly set.
  public var hasTradeExchange: Bool {return _storage._tradeExchange != nil}
  /// Clears the value of `tradeExchange`. Subsequent reads from it will return its default value.
  public mutating func clearTradeExchange() {_uniqueStorage()._tradeExchange = nil}

  /// PB_OFFSET + MNM_TRADE_ROUTE
  public var tradeRoute: String {
    get {return _storage._tradeRoute ?? String()}
    set {_uniqueStorage()._tradeRoute = newValue}
  }
  /// Returns true if `tradeRoute` has been explicitly set.
  public var hasTradeRoute: Bool {return _storage._tradeRoute != nil}
  /// Clears the value of `tradeRoute`. Subsequent reads from it will return its default value.
  public mutating func clearTradeRoute() {_uniqueStorage()._tradeRoute = nil}

  /// PB_OFFSET + MNM_EXCH_ORD_ID
  public var exchangeOrderID: String {
    get {return _storage._exchangeOrderID ?? String()}
    set {_uniqueStorage()._exchangeOrderID = newValue}
  }
  /// Returns true if `exchangeOrderID` has been explicitly set.
  public var hasExchangeOrderID: Bool {return _storage._exchangeOrderID != nil}
  /// Clears the value of `exchangeOrderID`. Subsequent reads from it will return its default value.
  public mutating func clearExchangeOrderID() {_uniqueStorage()._exchangeOrderID = nil}

  /// PB_OFFSET + MNM_INSTRUMENT_TYPE
  public var instrumentType: String {
    get {return _storage._instrumentType ?? String()}
    set {_uniqueStorage()._instrumentType = newValue}
  }
  /// Returns true if `instrumentType` has been explicitly set.
  public var hasInstrumentType: Bool {return _storage._instrumentType != nil}
  /// Clears the value of `instrumentType`. Subsequent reads from it will return its default value.
  public mutating func clearInstrumentType() {_uniqueStorage()._instrumentType = nil}

  /// PB_OFFSET + MNM_QUAN_TO_FILL
  public var quantity: Int32 {
    get {return _storage._quantity ?? 0}
    set {_uniqueStorage()._quantity = newValue}
  }
  /// Returns true if `quantity` has been explicitly set.
  public var hasQuantity: Bool {return _storage._quantity != nil}
  /// Clears the value of `quantity`. Subsequent reads from it will return its default value.
  public mutating func clearQuantity() {_uniqueStorage()._quantity = nil}

  /// PB_OFFSET + MNM_PRICE_TO_FILL
  public var price: Double {
    get {return _storage._price ?? 0}
    set {_uniqueStorage()._price = newValue}
  }
  /// Returns true if `price` has been explicitly set.
  public var hasPrice: Bool {return _storage._price != nil}
  /// Clears the value of `price`. Subsequent reads from it will return its default value.
  public mutating func clearPrice() {_uniqueStorage()._price = nil}

  /// PB_OFFSET + MNM_TRIGGER_PRICE
  public var triggerPrice: Double {
    get {return _storage._triggerPrice ?? 0}
    set {_uniqueStorage()._triggerPrice = newValue}
  }
  /// Returns true if `triggerPrice` has been explicitly set.
  public var hasTriggerPrice: Bool {return _storage._triggerPrice != nil}
  /// Clears the value of `triggerPrice`. Subsequent reads from it will return its default value.
  public mutating func clearTriggerPrice() {_uniqueStorage()._triggerPrice = nil}

  /// PB_OFFSET + MNM_TRANSACTION_TYPE
  public var transactionType: RtiRithmicOrderNotification.TransactionType {
    get {return _storage._transactionType ?? .buy}
    set {_uniqueStorage()._transactionType = newValue}
  }
  /// Returns true if `transactionType` has been explicitly set.
  public var hasTransactionType: Bool {return _storage._transactionType != nil}
  /// Clears the value of `transactionType`. Subsequent reads from it will return its default value.
  public mutating func clearTransactionType() {_uniqueStorage()._transactionType = nil}

  /// PB_OFFSET + MNM_ORDER_DURATION
  public var duration: RtiRithmicOrderNotification.Duration {
    get {return _storage._duration ?? .day}
    set {_uniqueStorage()._duration = newValue}
  }
  /// Returns true if `duration` has been explicitly set.
  public var hasDuration: Bool {return _storage._duration != nil}
  /// Clears the value of `duration`. Subsequent reads from it will return its default value.
  public mutating func clearDuration() {_uniqueStorage()._duration = nil}

  /// PB_OFFSET + MNM_PRICE_TYPE
  public var priceType: RtiRithmicOrderNotification.PriceType {
    get {return _storage._priceType ?? .limit}
    set {_uniqueStorage()._priceType = newValue}
  }
  /// Returns true if `priceType` has been explicitly set.
  public var hasPriceType: Bool {return _storage._priceType != nil}
  /// Clears the value of `priceType`. Subsequent reads from it will return its default value.
  public mutating func clearPriceType() {_uniqueStorage()._priceType = nil}

  /// PB_OFFSET + MNM_ORIG_PRICE_TYPE
  public var origPriceType: RtiRithmicOrderNotification.PriceType {
    get {return _storage._origPriceType ?? .limit}
    set {_uniqueStorage()._origPriceType = newValue}
  }
  /// Returns true if `origPriceType` has been explicitly set.
  public var hasOrigPriceType: Bool {return _storage._origPriceType != nil}
  /// Clears the value of `origPriceType`. Subsequent reads from it will return its default value.
  public mutating func clearOrigPriceType() {_uniqueStorage()._origPriceType = nil}

  /// PB_OFFSET + MNM_MANUAL_OR_AUTO
  public var manualOrAuto: RtiRithmicOrderNotification.OrderPlacement {
    get {return _storage._manualOrAuto ?? .manual}
    set {_uniqueStorage()._manualOrAuto = newValue}
  }
  /// Returns true if `manualOrAuto` has been explicitly set.
  public var hasManualOrAuto: Bool {return _storage._manualOrAuto != nil}
  /// Clears the value of `manualOrAuto`. Subsequent reads from it will return its default value.
  public mutating func clearManualOrAuto() {_uniqueStorage()._manualOrAuto = nil}

  /// PB_OFFSET + MNM_SEQUENCE_NUMBER
  public var sequenceNumber: String {
    get {return _storage._sequenceNumber ?? String()}
    set {_uniqueStorage()._sequenceNumber = newValue}
  }
  /// Returns true if `sequenceNumber` has been explicitly set.
  public var hasSequenceNumber: Bool {return _storage._sequenceNumber != nil}
  /// Clears the value of `sequenceNumber`. Subsequent reads from it will return its default value.
  public mutating func clearSequenceNumber() {_uniqueStorage()._sequenceNumber = nil}

  /// PB_OFFSET + MNM_ORIG_SEQUENCE_NUMBER
  public var origSequenceNumber: String {
    get {return _storage._origSequenceNumber ?? String()}
    set {_uniqueStorage()._origSequenceNumber = newValue}
  }
  /// Returns true if `origSequenceNumber` has been explicitly set.
  public var hasOrigSequenceNumber: Bool {return _storage._origSequenceNumber != nil}
  /// Clears the value of `origSequenceNumber`. Subsequent reads from it will return its default value.
  public mutating func clearOrigSequenceNumber() {_uniqueStorage()._origSequenceNumber = nil}

  /// PB_OFFSET + MNM_COR_SEQUENCE_NUMBER
  public var corSequenceNumber: String {
    get {return _storage._corSequenceNumber ?? String()}
    set {_uniqueStorage()._corSequenceNumber = newValue}
  }
  /// Returns true if `corSequenceNumber` has been explicitly set.
  public var hasCorSequenceNumber: Bool {return _storage._corSequenceNumber != nil}
  /// Clears the value of `corSequenceNumber`. Subsequent reads from it will return its default value.
  public mutating func clearCorSequenceNumber() {_uniqueStorage()._corSequenceNumber = nil}

  /// PB_OFFSET + MNM_CURRENCY
  public var currency: String {
    get {return _storage._currency ?? String()}
    set {_uniqueStorage()._currency = newValue}
  }
  /// Returns true if `currency` has been explicitly set.
  public var hasCurrency: Bool {return _storage._currency != nil}
  /// Clears the value of `currency`. Subsequent reads from it will return its default value.
  public mutating func clearCurrency() {_uniqueStorage()._currency = nil}

  /// PB_OFFSET + MNM_COUNTRY_CODE
  public var countryCode: String {
    get {return _storage._countryCode ?? String()}
    set {_uniqueStorage()._countryCode = newValue}
  }
  /// Returns true if `countryCode` has been explicitly set.
  public var hasCountryCode: Bool {return _storage._countryCode != nil}
  /// Clears the value of `countryCode`. Subsequent reads from it will return its default value.
  public mutating func clearCountryCode() {_uniqueStorage()._countryCode = nil}

  /// PB_OFFSET + MNM_TEXT
  public var text: String {
    get {return _storage._text ?? String()}
    set {_uniqueStorage()._text = newValue}
  }
  /// Returns true if `text` has been explicitly set.
  public var hasText: Bool {return _storage._text != nil}
  /// Clears the value of `text`. Subsequent reads from it will return its default value.
  public mutating func clearText() {_uniqueStorage()._text = nil}

  /// PB_OFFSET + MNM_REPORT_TEXT
  public var reportText: String {
    get {return _storage._reportText ?? String()}
    set {_uniqueStorage()._reportText = newValue}
  }
  /// Returns true if `reportText` has been explicitly set.
  public var hasReportText: Bool {return _storage._reportText != nil}
  /// Clears the value of `reportText`. Subsequent reads from it will return its default value.
  public mutating func clearReportText() {_uniqueStorage()._reportText = nil}

  /// PB_OFFSET + MNM_REMARKS
  public var remarks: String {
    get {return _storage._remarks ?? String()}
    set {_uniqueStorage()._remarks = newValue}
  }
  /// Returns true if `remarks` has been explicitly set.
  public var hasRemarks: Bool {return _storage._remarks != nil}
  /// Clears the value of `remarks`. Subsequent reads from it will return its default value.
  public mutating func clearRemarks() {_uniqueStorage()._remarks = nil}

  /// PB_OFFSET + MNM_SECONDS_SINCE_BOE
  public var ssboe: Int32 {
    get {return _storage._ssboe ?? 0}
    set {_uniqueStorage()._ssboe = newValue}
  }
  /// Returns true if `ssboe` has been explicitly set.
  public var hasSsboe: Bool {return _storage._ssboe != nil}
  /// Clears the value of `ssboe`. Subsequent reads from it will return its default value.
  public mutating func clearSsboe() {_uniqueStorage()._ssboe = nil}

  /// PB_OFFSET + MNM_USECS
  public var usecs: Int32 {
    get {return _storage._usecs ?? 0}
    set {_uniqueStorage()._usecs = newValue}
  }
  /// Returns true if `usecs` has been explicitly set.
  public var hasUsecs: Bool {return _storage._usecs != nil}
  /// Clears the value of `usecs`. Subsequent reads from it will return its default value.
  public mutating func clearUsecs() {_uniqueStorage()._usecs = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum NotifyType: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case orderRcvdFromClnt // = 1
    case modifyRcvdFromClnt // = 2
    case cancelRcvdFromClnt // = 3
    case openPending // = 4
    case modifyPending // = 5
    case cancelPending // = 6
    case orderRcvdByExchGtwy // = 7
    case modifyRcvdByExchGtwy // = 8
    case cancelRcvdByExchGtwy // = 9
    case orderSentToExch // = 10
    case modifySentToExch // = 11
    case cancelSentToExch // = 12
    case `open` // = 13
    case modified // = 14
    case complete // = 15
    case modificationFailed // = 16
    case cancellationFailed // = 17
    case triggerPending // = 18
    case generic // = 19
    case linkOrdersFailed // = 20

    public init() {
      self = .orderRcvdFromClnt
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .orderRcvdFromClnt
      case 2: self = .modifyRcvdFromClnt
      case 3: self = .cancelRcvdFromClnt
      case 4: self = .openPending
      case 5: self = .modifyPending
      case 6: self = .cancelPending
      case 7: self = .orderRcvdByExchGtwy
      case 8: self = .modifyRcvdByExchGtwy
      case 9: self = .cancelRcvdByExchGtwy
      case 10: self = .orderSentToExch
      case 11: self = .modifySentToExch
      case 12: self = .cancelSentToExch
      case 13: self = .open
      case 14: self = .modified
      case 15: self = .complete
      case 16: self = .modificationFailed
      case 17: self = .cancellationFailed
      case 18: self = .triggerPending
      case 19: self = .generic
      case 20: self = .linkOrdersFailed
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .orderRcvdFromClnt: return 1
      case .modifyRcvdFromClnt: return 2
      case .cancelRcvdFromClnt: return 3
      case .openPending: return 4
      case .modifyPending: return 5
      case .cancelPending: return 6
      case .orderRcvdByExchGtwy: return 7
      case .modifyRcvdByExchGtwy: return 8
      case .cancelRcvdByExchGtwy: return 9
      case .orderSentToExch: return 10
      case .modifySentToExch: return 11
      case .cancelSentToExch: return 12
      case .open: return 13
      case .modified: return 14
      case .complete: return 15
      case .modificationFailed: return 16
      case .cancellationFailed: return 17
      case .triggerPending: return 18
      case .generic: return 19
      case .linkOrdersFailed: return 20
      }
    }

  }

  public enum TransactionType: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case buy // = 1
    case sell // = 2

    public init() {
      self = .buy
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .buy
      case 2: self = .sell
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .buy: return 1
      case .sell: return 2
      }
    }

  }

  public enum Duration: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case day // = 1
    case gtc // = 2
    case ioc // = 3
    case fok // = 4

    public init() {
      self = .day
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .day
      case 2: self = .gtc
      case 3: self = .ioc
      case 4: self = .fok
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .day: return 1
      case .gtc: return 2
      case .ioc: return 3
      case .fok: return 4
      }
    }

  }

  public enum PriceType: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case limit // = 1
    case market // = 2
    case stopLimit // = 3
    case stopMarket // = 4

    public init() {
      self = .limit
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .limit
      case 2: self = .market
      case 3: self = .stopLimit
      case 4: self = .stopMarket
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .limit: return 1
      case .market: return 2
      case .stopLimit: return 3
      case .stopMarket: return 4
      }
    }

  }

  public enum OrderPlacement: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case manual // = 1
    case auto // = 2

    public init() {
      self = .manual
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .manual
      case 2: self = .auto
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .manual: return 1
      case .auto: return 2
      }
    }

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

#if swift(>=4.2)

extension RtiRithmicOrderNotification.NotifyType: CaseIterable {
  // Support synthesized by the compiler.
}

extension RtiRithmicOrderNotification.TransactionType: CaseIterable {
  // Support synthesized by the compiler.
}

extension RtiRithmicOrderNotification.Duration: CaseIterable {
  // Support synthesized by the compiler.
}

extension RtiRithmicOrderNotification.PriceType: CaseIterable {
  // Support synthesized by the compiler.
}

extension RtiRithmicOrderNotification.OrderPlacement: CaseIterable {
  // Support synthesized by the compiler.
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rti"

extension RtiRithmicOrderNotification: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RithmicOrderNotification"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    154467: .standard(proto: "template_id"),
    153625: .standard(proto: "notify_type"),
    110121: .standard(proto: "is_snapshot"),
    110303: .same(proto: "status"),
    110300: .standard(proto: "basket_id"),
    154497: .standard(proto: "original_basket_id"),
    154013: .standard(proto: "fcm_id"),
    154014: .standard(proto: "ib_id"),
    131003: .standard(proto: "user_id"),
    154008: .standard(proto: "account_id"),
    110100: .same(proto: "symbol"),
    110101: .same(proto: "exchange"),
    112021: .standard(proto: "trade_exchange"),
    112016: .standard(proto: "trade_route"),
    149238: .standard(proto: "exchange_order_id"),
    110116: .standard(proto: "instrument_type"),
    112004: .same(proto: "quantity"),
    110306: .same(proto: "price"),
    149247: .standard(proto: "trigger_price"),
    112003: .standard(proto: "transaction_type"),
    112005: .same(proto: "duration"),
    112008: .standard(proto: "price_type"),
    154770: .standard(proto: "orig_price_type"),
    154710: .standard(proto: "manual_or_auto"),
    112002: .standard(proto: "sequence_number"),
    149263: .standard(proto: "orig_sequence_number"),
    149264: .standard(proto: "cor_sequence_number"),
    154382: .same(proto: "currency"),
    154172: .standard(proto: "country_code"),
    120008: .same(proto: "text"),
    120028: .standard(proto: "report_text"),
    154806: .same(proto: "remarks"),
    150100: .same(proto: "ssboe"),
    150101: .same(proto: "usecs"),
  ]

  fileprivate class _StorageClass {
    var _templateID: Int32? = nil
    var _notifyType: RtiRithmicOrderNotification.NotifyType? = nil
    var _isSnapshot: Bool? = nil
    var _status: String? = nil
    var _basketID: String? = nil
    var _originalBasketID: String? = nil
    var _fcmID: String? = nil
    var _ibID: String? = nil
    var _userID: String? = nil
    var _accountID: String? = nil
    var _symbol: String? = nil
    var _exchange: String? = nil
    var _tradeExchange: String? = nil
    var _tradeRoute: String? = nil
    var _exchangeOrderID: String? = nil
    var _instrumentType: String? = nil
    var _quantity: Int32? = nil
    var _price: Double? = nil
    var _triggerPrice: Double? = nil
    var _transactionType: RtiRithmicOrderNotification.TransactionType? = nil
    var _duration: RtiRithmicOrderNotification.Duration? = nil
    var _priceType: RtiRithmicOrderNotification.PriceType? = nil
    var _origPriceType: RtiRithmicOrderNotification.PriceType? = nil
    var _manualOrAuto: RtiRithmicOrderNotification.OrderPlacement? = nil
    var _sequenceNumber: String? = nil
    var _origSequenceNumber: String? = nil
    var _corSequenceNumber: String? = nil
    var _currency: String? = nil
    var _countryCode: String? = nil
    var _text: String? = nil
    var _reportText: String? = nil
    var _remarks: String? = nil
    var _ssboe: Int32? = nil
    var _usecs: Int32? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _templateID = source._templateID
      _notifyType = source._notifyType
      _isSnapshot = source._isSnapshot
      _status = source._status
      _basketID = source._basketID
      _originalBasketID = source._originalBasketID
      _fcmID = source._fcmID
      _ibID = source._ibID
      _userID = source._userID
      _accountID = source._accountID
      _symbol = source._symbol
      _exchange = source._exchange
      _tradeExchange = source._tradeExchange
      _tradeRoute = source._tradeRoute
      _exchangeOrderID = source._exchangeOrderID
      _instrumentType = source._instrumentType
      _quantity = source._quantity
      _price = source._price
      _triggerPrice = source._triggerPrice
      _transactionType = source._transactionType
      _duration = source._duration
      _priceType = source._priceType
      _origPriceType = source._origPriceType
      _manualOrAuto = source._manualOrAuto
      _sequenceNumber = source._sequenceNumber
      _origSequenceNumber = source._origSequenceNumber
      _corSequenceNumber = source._corSequenceNumber
      _currency = source._currency
      _countryCode = source._countryCode
      _text = source._text
      _reportText = source._reportText
      _remarks = source._remarks
      _ssboe = source._ssboe
      _usecs = source._usecs
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._templateID == nil {return false}
      return true
    }
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 110100: try decoder.decodeSingularStringField(value: &_storage._symbol)
        case 110101: try decoder.decodeSingularStringField(value: &_storage._exchange)
        case 110116: try decoder.decodeSingularStringField(value: &_storage._instrumentType)
        case 110121: try decoder.decodeSingularBoolField(value: &_storage._isSnapshot)
        case 110300: try decoder.decodeSingularStringField(value: &_storage._basketID)
        case 110303: try decoder.decodeSingularStringField(value: &_storage._status)
        case 110306: try decoder.decodeSingularDoubleField(value: &_storage._price)
        case 112002: try decoder.decodeSingularStringField(value: &_storage._sequenceNumber)
        case 112003: try decoder.decodeSingularEnumField(value: &_storage._transactionType)
        case 112004: try decoder.decodeSingularInt32Field(value: &_storage._quantity)
        case 112005: try decoder.decodeSingularEnumField(value: &_storage._duration)
        case 112008: try decoder.decodeSingularEnumField(value: &_storage._priceType)
        case 112016: try decoder.decodeSingularStringField(value: &_storage._tradeRoute)
        case 112021: try decoder.decodeSingularStringField(value: &_storage._tradeExchange)
        case 120008: try decoder.decodeSingularStringField(value: &_storage._text)
        case 120028: try decoder.decodeSingularStringField(value: &_storage._reportText)
        case 131003: try decoder.decodeSingularStringField(value: &_storage._userID)
        case 149238: try decoder.decodeSingularStringField(value: &_storage._exchangeOrderID)
        case 149247: try decoder.decodeSingularDoubleField(value: &_storage._triggerPrice)
        case 149263: try decoder.decodeSingularStringField(value: &_storage._origSequenceNumber)
        case 149264: try decoder.decodeSingularStringField(value: &_storage._corSequenceNumber)
        case 150100: try decoder.decodeSingularInt32Field(value: &_storage._ssboe)
        case 150101: try decoder.decodeSingularInt32Field(value: &_storage._usecs)
        case 153625: try decoder.decodeSingularEnumField(value: &_storage._notifyType)
        case 154008: try decoder.decodeSingularStringField(value: &_storage._accountID)
        case 154013: try decoder.decodeSingularStringField(value: &_storage._fcmID)
        case 154014: try decoder.decodeSingularStringField(value: &_storage._ibID)
        case 154172: try decoder.decodeSingularStringField(value: &_storage._countryCode)
        case 154382: try decoder.decodeSingularStringField(value: &_storage._currency)
        case 154467: try decoder.decodeSingularInt32Field(value: &_storage._templateID)
        case 154497: try decoder.decodeSingularStringField(value: &_storage._originalBasketID)
        case 154710: try decoder.decodeSingularEnumField(value: &_storage._manualOrAuto)
        case 154770: try decoder.decodeSingularEnumField(value: &_storage._origPriceType)
        case 154806: try decoder.decodeSingularStringField(value: &_storage._remarks)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._symbol {
        try visitor.visitSingularStringField(value: v, fieldNumber: 110100)
      }
      if let v = _storage._exchange {
        try visitor.visitSingularStringField(value: v, fieldNumber: 110101)
      }
      if let v = _storage._instrumentType {
        try visitor.visitSingularStringField(value: v, fieldNumber: 110116)
      }
      if let v = _storage._isSnapshot {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 110121)
      }
      if let v = _storage._basketID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 110300)
      }
      if let v = _storage._status {
        try visitor.visitSingularStringField(value: v, fieldNumber: 110303)
      }
      if let v = _storage._price {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 110306)
      }
      if let v = _storage._sequenceNumber {
        try visitor.visitSingularStringField(value: v, fieldNumber: 112002)
      }
      if let v = _storage._transactionType {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 112003)
      }
      if let v = _storage._quantity {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 112004)
      }
      if let v = _storage._duration {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 112005)
      }
      if let v = _storage._priceType {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 112008)
      }
      if let v = _storage._tradeRoute {
        try visitor.visitSingularStringField(value: v, fieldNumber: 112016)
      }
      if let v = _storage._tradeExchange {
        try visitor.visitSingularStringField(value: v, fieldNumber: 112021)
      }
      if let v = _storage._text {
        try visitor.visitSingularStringField(value: v, fieldNumber: 120008)
      }
      if let v = _storage._reportText {
        try visitor.visitSingularStringField(value: v, fieldNumber: 120028)
      }
      if let v = _storage._userID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 131003)
      }
      if let v = _storage._exchangeOrderID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 149238)
      }
      if let v = _storage._triggerPrice {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 149247)
      }
      if let v = _storage._origSequenceNumber {
        try visitor.visitSingularStringField(value: v, fieldNumber: 149263)
      }
      if let v = _storage._corSequenceNumber {
        try visitor.visitSingularStringField(value: v, fieldNumber: 149264)
      }
      if let v = _storage._ssboe {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150100)
      }
      if let v = _storage._usecs {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150101)
      }
      if let v = _storage._notifyType {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 153625)
      }
      if let v = _storage._accountID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 154008)
      }
      if let v = _storage._fcmID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 154013)
      }
      if let v = _storage._ibID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 154014)
      }
      if let v = _storage._countryCode {
        try visitor.visitSingularStringField(value: v, fieldNumber: 154172)
      }
      if let v = _storage._currency {
        try visitor.visitSingularStringField(value: v, fieldNumber: 154382)
      }
      if let v = _storage._templateID {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 154467)
      }
      if let v = _storage._originalBasketID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 154497)
      }
      if let v = _storage._manualOrAuto {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 154710)
      }
      if let v = _storage._origPriceType {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 154770)
      }
      if let v = _storage._remarks {
        try visitor.visitSingularStringField(value: v, fieldNumber: 154806)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RtiRithmicOrderNotification, rhs: RtiRithmicOrderNotification) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._templateID != rhs_storage._templateID {return false}
        if _storage._notifyType != rhs_storage._notifyType {return false}
        if _storage._isSnapshot != rhs_storage._isSnapshot {return false}
        if _storage._status != rhs_storage._status {return false}
        if _storage._basketID != rhs_storage._basketID {return false}
        if _storage._originalBasketID != rhs_storage._originalBasketID {return false}
        if _storage._fcmID != rhs_storage._fcmID {return false}
        if _storage._ibID != rhs_storage._ibID {return false}
        if _storage._userID != rhs_storage._userID {return false}
        if _storage._accountID != rhs_storage._accountID {return false}
        if _storage._symbol != rhs_storage._symbol {return false}
        if _storage._exchange != rhs_storage._exchange {return false}
        if _storage._tradeExchange != rhs_storage._tradeExchange {return false}
        if _storage._tradeRoute != rhs_storage._tradeRoute {return false}
        if _storage._exchangeOrderID != rhs_storage._exchangeOrderID {return false}
        if _storage._instrumentType != rhs_storage._instrumentType {return false}
        if _storage._quantity != rhs_storage._quantity {return false}
        if _storage._price != rhs_storage._price {return false}
        if _storage._triggerPrice != rhs_storage._triggerPrice {return false}
        if _storage._transactionType != rhs_storage._transactionType {return false}
        if _storage._duration != rhs_storage._duration {return false}
        if _storage._priceType != rhs_storage._priceType {return false}
        if _storage._origPriceType != rhs_storage._origPriceType {return false}
        if _storage._manualOrAuto != rhs_storage._manualOrAuto {return false}
        if _storage._sequenceNumber != rhs_storage._sequenceNumber {return false}
        if _storage._origSequenceNumber != rhs_storage._origSequenceNumber {return false}
        if _storage._corSequenceNumber != rhs_storage._corSequenceNumber {return false}
        if _storage._currency != rhs_storage._currency {return false}
        if _storage._countryCode != rhs_storage._countryCode {return false}
        if _storage._text != rhs_storage._text {return false}
        if _storage._reportText != rhs_storage._reportText {return false}
        if _storage._remarks != rhs_storage._remarks {return false}
        if _storage._ssboe != rhs_storage._ssboe {return false}
        if _storage._usecs != rhs_storage._usecs {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RtiRithmicOrderNotification.NotifyType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "ORDER_RCVD_FROM_CLNT"),
    2: .same(proto: "MODIFY_RCVD_FROM_CLNT"),
    3: .same(proto: "CANCEL_RCVD_FROM_CLNT"),
    4: .same(proto: "OPEN_PENDING"),
    5: .same(proto: "MODIFY_PENDING"),
    6: .same(proto: "CANCEL_PENDING"),
    7: .same(proto: "ORDER_RCVD_BY_EXCH_GTWY"),
    8: .same(proto: "MODIFY_RCVD_BY_EXCH_GTWY"),
    9: .same(proto: "CANCEL_RCVD_BY_EXCH_GTWY"),
    10: .same(proto: "ORDER_SENT_TO_EXCH"),
    11: .same(proto: "MODIFY_SENT_TO_EXCH"),
    12: .same(proto: "CANCEL_SENT_TO_EXCH"),
    13: .same(proto: "OPEN"),
    14: .same(proto: "MODIFIED"),
    15: .same(proto: "COMPLETE"),
    16: .same(proto: "MODIFICATION_FAILED"),
    17: .same(proto: "CANCELLATION_FAILED"),
    18: .same(proto: "TRIGGER_PENDING"),
    19: .same(proto: "GENERIC"),
    20: .same(proto: "LINK_ORDERS_FAILED"),
  ]
}

extension RtiRithmicOrderNotification.TransactionType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "BUY"),
    2: .same(proto: "SELL"),
  ]
}

extension RtiRithmicOrderNotification.Duration: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "DAY"),
    2: .same(proto: "GTC"),
    3: .same(proto: "IOC"),
    4: .same(proto: "FOK"),
  ]
}

extension RtiRithmicOrderNotification.PriceType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "LIMIT"),
    2: .same(proto: "MARKET"),
    3: .same(proto: "STOP_LIMIT"),
    4: .same(proto: "STOP_MARKET"),
  ]
}

extension RtiRithmicOrderNotification.OrderPlacement: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "MANUAL"),
    2: .same(proto: "AUTO"),
  ]
}
