// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: DepthByOrder.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// PB_OFFSET = 100000 , is the offset added for each MNM field id
public struct RtiDepthByOrder {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// PB_OFFSET + MNM_TEMPLATE_ID
  public var templateID: Int32 {
    get {return _storage._templateID ?? 0}
    set {_uniqueStorage()._templateID = newValue}
  }
  /// Returns true if `templateID` has been explicitly set.
  public var hasTemplateID: Bool {return _storage._templateID != nil}
  /// Clears the value of `templateID`. Subsequent reads from it will return its default value.
  public mutating func clearTemplateID() {_uniqueStorage()._templateID = nil}

  /// PB_OFFSET + MNM_SYMBOL
  public var symbol: String {
    get {return _storage._symbol ?? String()}
    set {_uniqueStorage()._symbol = newValue}
  }
  /// Returns true if `symbol` has been explicitly set.
  public var hasSymbol: Bool {return _storage._symbol != nil}
  /// Clears the value of `symbol`. Subsequent reads from it will return its default value.
  public mutating func clearSymbol() {_uniqueStorage()._symbol = nil}

  /// PB_OFFSET + MNM_EXCHANGE
  public var exchange: String {
    get {return _storage._exchange ?? String()}
    set {_uniqueStorage()._exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {return _storage._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {_uniqueStorage()._exchange = nil}

  /// PB_OFFSET + MNM_SEQUENCE_NUMBER
  public var sequenceNumber: UInt64 {
    get {return _storage._sequenceNumber ?? 0}
    set {_uniqueStorage()._sequenceNumber = newValue}
  }
  /// Returns true if `sequenceNumber` has been explicitly set.
  public var hasSequenceNumber: Bool {return _storage._sequenceNumber != nil}
  /// Clears the value of `sequenceNumber`. Subsequent reads from it will return its default value.
  public mutating func clearSequenceNumber() {_uniqueStorage()._sequenceNumber = nil}

  /// PB_OFFSET + MNM_UPDATE_TYPE
  public var updateType: [RtiDepthByOrder.UpdateType] {
    get {return _storage._updateType}
    set {_uniqueStorage()._updateType = newValue}
  }

  /// PB_OFFSET + MNM_MARKET_DEPTH_SIDE
  public var transactionType: [RtiDepthByOrder.TransactionType] {
    get {return _storage._transactionType}
    set {_uniqueStorage()._transactionType = newValue}
  }

  /// PB_OFFSET + MNM_MARKET_DEPTH_PRICE
  public var depthPrice: [Double] {
    get {return _storage._depthPrice}
    set {_uniqueStorage()._depthPrice = newValue}
  }

  /// PB_OFFSET + MNM_PREVIOUS_MARKET_DEPTH_PRICE
  public var prevDepthPrice: [Double] {
    get {return _storage._prevDepthPrice}
    set {_uniqueStorage()._prevDepthPrice = newValue}
  }

  /// PB_OFFSET + MNM_PREVIOUS_MARKET_DEPTH_PRICE_FLAG
  public var prevDepthPriceFlag: [Bool] {
    get {return _storage._prevDepthPriceFlag}
    set {_uniqueStorage()._prevDepthPriceFlag = newValue}
  }

  /// PB_OFFSET + MNM_MARKET_DEPTH_SIZE
  public var depthSize: [Int32] {
    get {return _storage._depthSize}
    set {_uniqueStorage()._depthSize = newValue}
  }

  /// PB_OFFSET + MNM_MARKET_DEPTH_ORDER_PRIORITY
  public var depthOrderPriority: [UInt64] {
    get {return _storage._depthOrderPriority}
    set {_uniqueStorage()._depthOrderPriority = newValue}
  }

  /// PB_OFFSET + MNM_EXCH_ORD_ID
  public var exchangeOrderID: [String] {
    get {return _storage._exchangeOrderID}
    set {_uniqueStorage()._exchangeOrderID = newValue}
  }

  /// PB_OFFSET + MNM_SECONDS_SINCE_BOE
  public var ssboe: Int32 {
    get {return _storage._ssboe ?? 0}
    set {_uniqueStorage()._ssboe = newValue}
  }
  /// Returns true if `ssboe` has been explicitly set.
  public var hasSsboe: Bool {return _storage._ssboe != nil}
  /// Clears the value of `ssboe`. Subsequent reads from it will return its default value.
  public mutating func clearSsboe() {_uniqueStorage()._ssboe = nil}

  /// PB_OFFSET + MNM_USECS
  public var usecs: Int32 {
    get {return _storage._usecs ?? 0}
    set {_uniqueStorage()._usecs = newValue}
  }
  /// Returns true if `usecs` has been explicitly set.
  public var hasUsecs: Bool {return _storage._usecs != nil}
  /// Clears the value of `usecs`. Subsequent reads from it will return its default value.
  public mutating func clearUsecs() {_uniqueStorage()._usecs = nil}

  /// PB_OFFSET + MNM_SOURCE_SSBOE
  public var sourceSsboe: Int32 {
    get {return _storage._sourceSsboe ?? 0}
    set {_uniqueStorage()._sourceSsboe = newValue}
  }
  /// Returns true if `sourceSsboe` has been explicitly set.
  public var hasSourceSsboe: Bool {return _storage._sourceSsboe != nil}
  /// Clears the value of `sourceSsboe`. Subsequent reads from it will return its default value.
  public mutating func clearSourceSsboe() {_uniqueStorage()._sourceSsboe = nil}

  /// PB_OFFSET + MNM_SOURCE_USECS
  public var sourceUsecs: Int32 {
    get {return _storage._sourceUsecs ?? 0}
    set {_uniqueStorage()._sourceUsecs = newValue}
  }
  /// Returns true if `sourceUsecs` has been explicitly set.
  public var hasSourceUsecs: Bool {return _storage._sourceUsecs != nil}
  /// Clears the value of `sourceUsecs`. Subsequent reads from it will return its default value.
  public mutating func clearSourceUsecs() {_uniqueStorage()._sourceUsecs = nil}

  /// PB_OFFSET + MNM_SOURCE_NSECS
  public var sourceNsecs: Int32 {
    get {return _storage._sourceNsecs ?? 0}
    set {_uniqueStorage()._sourceNsecs = newValue}
  }
  /// Returns true if `sourceNsecs` has been explicitly set.
  public var hasSourceNsecs: Bool {return _storage._sourceNsecs != nil}
  /// Clears the value of `sourceNsecs`. Subsequent reads from it will return its default value.
  public mutating func clearSourceNsecs() {_uniqueStorage()._sourceNsecs = nil}

  /// PB_OFFSET + MNM_JOP_SSBOE
  public var jopSsboe: Int32 {
    get {return _storage._jopSsboe ?? 0}
    set {_uniqueStorage()._jopSsboe = newValue}
  }
  /// Returns true if `jopSsboe` has been explicitly set.
  public var hasJopSsboe: Bool {return _storage._jopSsboe != nil}
  /// Clears the value of `jopSsboe`. Subsequent reads from it will return its default value.
  public mutating func clearJopSsboe() {_uniqueStorage()._jopSsboe = nil}

  /// PB_OFFSET + MNM_JOP_NSECS
  public var jopNsecs: Int32 {
    get {return _storage._jopNsecs ?? 0}
    set {_uniqueStorage()._jopNsecs = newValue}
  }
  /// Returns true if `jopNsecs` has been explicitly set.
  public var hasJopNsecs: Bool {return _storage._jopNsecs != nil}
  /// Clears the value of `jopNsecs`. Subsequent reads from it will return its default value.
  public mutating func clearJopNsecs() {_uniqueStorage()._jopNsecs = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum TransactionType: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case buy // = 1
    case sell // = 2

    public init() {
      self = .buy
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .buy
      case 2: self = .sell
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .buy: return 1
      case .sell: return 2
      }
    }

  }

  public enum UpdateType: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case new // = 1
    case change // = 2
    case delete // = 3

    public init() {
      self = .new
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .new
      case 2: self = .change
      case 3: self = .delete
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .new: return 1
      case .change: return 2
      case .delete: return 3
      }
    }

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

#if swift(>=4.2)

extension RtiDepthByOrder.TransactionType: CaseIterable {
  // Support synthesized by the compiler.
}

extension RtiDepthByOrder.UpdateType: CaseIterable {
  // Support synthesized by the compiler.
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rti"

extension RtiDepthByOrder: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DepthByOrder"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    154467: .standard(proto: "template_id"),
    110100: .same(proto: "symbol"),
    110101: .same(proto: "exchange"),
    112002: .standard(proto: "sequence_number"),
    110121: .standard(proto: "update_type"),
    153612: .standard(proto: "transaction_type"),
    154405: .standard(proto: "depth_price"),
    154906: .standard(proto: "prev_depth_price"),
    154930: .standard(proto: "prev_depth_price_flag"),
    154406: .standard(proto: "depth_size"),
    153613: .standard(proto: "depth_order_priority"),
    149238: .standard(proto: "exchange_order_id"),
    150100: .same(proto: "ssboe"),
    150101: .same(proto: "usecs"),
    150400: .standard(proto: "source_ssboe"),
    150401: .standard(proto: "source_usecs"),
    150404: .standard(proto: "source_nsecs"),
    150600: .standard(proto: "jop_ssboe"),
    150604: .standard(proto: "jop_nsecs"),
  ]

  fileprivate class _StorageClass {
    var _templateID: Int32? = nil
    var _symbol: String? = nil
    var _exchange: String? = nil
    var _sequenceNumber: UInt64? = nil
    var _updateType: [RtiDepthByOrder.UpdateType] = []
    var _transactionType: [RtiDepthByOrder.TransactionType] = []
    var _depthPrice: [Double] = []
    var _prevDepthPrice: [Double] = []
    var _prevDepthPriceFlag: [Bool] = []
    var _depthSize: [Int32] = []
    var _depthOrderPriority: [UInt64] = []
    var _exchangeOrderID: [String] = []
    var _ssboe: Int32? = nil
    var _usecs: Int32? = nil
    var _sourceSsboe: Int32? = nil
    var _sourceUsecs: Int32? = nil
    var _sourceNsecs: Int32? = nil
    var _jopSsboe: Int32? = nil
    var _jopNsecs: Int32? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _templateID = source._templateID
      _symbol = source._symbol
      _exchange = source._exchange
      _sequenceNumber = source._sequenceNumber
      _updateType = source._updateType
      _transactionType = source._transactionType
      _depthPrice = source._depthPrice
      _prevDepthPrice = source._prevDepthPrice
      _prevDepthPriceFlag = source._prevDepthPriceFlag
      _depthSize = source._depthSize
      _depthOrderPriority = source._depthOrderPriority
      _exchangeOrderID = source._exchangeOrderID
      _ssboe = source._ssboe
      _usecs = source._usecs
      _sourceSsboe = source._sourceSsboe
      _sourceUsecs = source._sourceUsecs
      _sourceNsecs = source._sourceNsecs
      _jopSsboe = source._jopSsboe
      _jopNsecs = source._jopNsecs
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._templateID == nil {return false}
      return true
    }
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 110100: try decoder.decodeSingularStringField(value: &_storage._symbol)
        case 110101: try decoder.decodeSingularStringField(value: &_storage._exchange)
        case 110121: try decoder.decodeRepeatedEnumField(value: &_storage._updateType)
        case 112002: try decoder.decodeSingularUInt64Field(value: &_storage._sequenceNumber)
        case 149238: try decoder.decodeRepeatedStringField(value: &_storage._exchangeOrderID)
        case 150100: try decoder.decodeSingularInt32Field(value: &_storage._ssboe)
        case 150101: try decoder.decodeSingularInt32Field(value: &_storage._usecs)
        case 150400: try decoder.decodeSingularInt32Field(value: &_storage._sourceSsboe)
        case 150401: try decoder.decodeSingularInt32Field(value: &_storage._sourceUsecs)
        case 150404: try decoder.decodeSingularInt32Field(value: &_storage._sourceNsecs)
        case 150600: try decoder.decodeSingularInt32Field(value: &_storage._jopSsboe)
        case 150604: try decoder.decodeSingularInt32Field(value: &_storage._jopNsecs)
        case 153612: try decoder.decodeRepeatedEnumField(value: &_storage._transactionType)
        case 153613: try decoder.decodeRepeatedUInt64Field(value: &_storage._depthOrderPriority)
        case 154405: try decoder.decodeRepeatedDoubleField(value: &_storage._depthPrice)
        case 154406: try decoder.decodeRepeatedInt32Field(value: &_storage._depthSize)
        case 154467: try decoder.decodeSingularInt32Field(value: &_storage._templateID)
        case 154906: try decoder.decodeRepeatedDoubleField(value: &_storage._prevDepthPrice)
        case 154930: try decoder.decodeRepeatedBoolField(value: &_storage._prevDepthPriceFlag)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._symbol {
        try visitor.visitSingularStringField(value: v, fieldNumber: 110100)
      }
      if let v = _storage._exchange {
        try visitor.visitSingularStringField(value: v, fieldNumber: 110101)
      }
      if !_storage._updateType.isEmpty {
        try visitor.visitRepeatedEnumField(value: _storage._updateType, fieldNumber: 110121)
      }
      if let v = _storage._sequenceNumber {
        try visitor.visitSingularUInt64Field(value: v, fieldNumber: 112002)
      }
      if !_storage._exchangeOrderID.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._exchangeOrderID, fieldNumber: 149238)
      }
      if let v = _storage._ssboe {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150100)
      }
      if let v = _storage._usecs {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150101)
      }
      if let v = _storage._sourceSsboe {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150400)
      }
      if let v = _storage._sourceUsecs {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150401)
      }
      if let v = _storage._sourceNsecs {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150404)
      }
      if let v = _storage._jopSsboe {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150600)
      }
      if let v = _storage._jopNsecs {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150604)
      }
      if !_storage._transactionType.isEmpty {
        try visitor.visitRepeatedEnumField(value: _storage._transactionType, fieldNumber: 153612)
      }
      if !_storage._depthOrderPriority.isEmpty {
        try visitor.visitRepeatedUInt64Field(value: _storage._depthOrderPriority, fieldNumber: 153613)
      }
      if !_storage._depthPrice.isEmpty {
        try visitor.visitRepeatedDoubleField(value: _storage._depthPrice, fieldNumber: 154405)
      }
      if !_storage._depthSize.isEmpty {
        try visitor.visitRepeatedInt32Field(value: _storage._depthSize, fieldNumber: 154406)
      }
      if let v = _storage._templateID {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 154467)
      }
      if !_storage._prevDepthPrice.isEmpty {
        try visitor.visitRepeatedDoubleField(value: _storage._prevDepthPrice, fieldNumber: 154906)
      }
      if !_storage._prevDepthPriceFlag.isEmpty {
        try visitor.visitRepeatedBoolField(value: _storage._prevDepthPriceFlag, fieldNumber: 154930)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RtiDepthByOrder, rhs: RtiDepthByOrder) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._templateID != rhs_storage._templateID {return false}
        if _storage._symbol != rhs_storage._symbol {return false}
        if _storage._exchange != rhs_storage._exchange {return false}
        if _storage._sequenceNumber != rhs_storage._sequenceNumber {return false}
        if _storage._updateType != rhs_storage._updateType {return false}
        if _storage._transactionType != rhs_storage._transactionType {return false}
        if _storage._depthPrice != rhs_storage._depthPrice {return false}
        if _storage._prevDepthPrice != rhs_storage._prevDepthPrice {return false}
        if _storage._prevDepthPriceFlag != rhs_storage._prevDepthPriceFlag {return false}
        if _storage._depthSize != rhs_storage._depthSize {return false}
        if _storage._depthOrderPriority != rhs_storage._depthOrderPriority {return false}
        if _storage._exchangeOrderID != rhs_storage._exchangeOrderID {return false}
        if _storage._ssboe != rhs_storage._ssboe {return false}
        if _storage._usecs != rhs_storage._usecs {return false}
        if _storage._sourceSsboe != rhs_storage._sourceSsboe {return false}
        if _storage._sourceUsecs != rhs_storage._sourceUsecs {return false}
        if _storage._sourceNsecs != rhs_storage._sourceNsecs {return false}
        if _storage._jopSsboe != rhs_storage._jopSsboe {return false}
        if _storage._jopNsecs != rhs_storage._jopNsecs {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RtiDepthByOrder.TransactionType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "BUY"),
    2: .same(proto: "SELL"),
  ]
}

extension RtiDepthByOrder.UpdateType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "NEW"),
    2: .same(proto: "CHANGE"),
    3: .same(proto: "DELETE"),
  ]
}
