// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: LastTrade.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// PB_OFFSET = 100000, is the offset added for each MNM field id
public struct RtiLastTrade {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// PB_OFFSET + MNM_TEMPLATE_ID
  public var templateID: Int32 {
    get {return _storage._templateID ?? 0}
    set {_uniqueStorage()._templateID = newValue}
  }
  /// Returns true if `templateID` has been explicitly set.
  public var hasTemplateID: Bool {return _storage._templateID != nil}
  /// Clears the value of `templateID`. Subsequent reads from it will return its default value.
  public mutating func clearTemplateID() {_uniqueStorage()._templateID = nil}

  /// PB_OFFSET + MNM_SYMBOL
  public var symbol: String {
    get {return _storage._symbol ?? String()}
    set {_uniqueStorage()._symbol = newValue}
  }
  /// Returns true if `symbol` has been explicitly set.
  public var hasSymbol: Bool {return _storage._symbol != nil}
  /// Clears the value of `symbol`. Subsequent reads from it will return its default value.
  public mutating func clearSymbol() {_uniqueStorage()._symbol = nil}

  /// PB_OFFSET + MNM_EXCHANGE
  public var exchange: String {
    get {return _storage._exchange ?? String()}
    set {_uniqueStorage()._exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {return _storage._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {_uniqueStorage()._exchange = nil}

  /// PB_OFFSET + MNM_PRICING_INDICATOR
  public var presenceBits: UInt32 {
    get {return _storage._presenceBits ?? 0}
    set {_uniqueStorage()._presenceBits = newValue}
  }
  /// Returns true if `presenceBits` has been explicitly set.
  public var hasPresenceBits: Bool {return _storage._presenceBits != nil}
  /// Clears the value of `presenceBits`. Subsequent reads from it will return its default value.
  public mutating func clearPresenceBits() {_uniqueStorage()._presenceBits = nil}

  /// PB_OFFSET + MNM_DISPLAY_INDICATOR
  public var clearBits_p: UInt32 {
    get {return _storage._clearBits_p ?? 0}
    set {_uniqueStorage()._clearBits_p = newValue}
  }
  /// Returns true if `clearBits_p` has been explicitly set.
  public var hasClearBits_p: Bool {return _storage._clearBits_p != nil}
  /// Clears the value of `clearBits_p`. Subsequent reads from it will return its default value.
  public mutating func clearClearBits_p() {_uniqueStorage()._clearBits_p = nil}

  /// PB_OFFSET + MNM_UPDATE_TYPE               
  public var isSnapshot: Bool {
    get {return _storage._isSnapshot ?? false}
    set {_uniqueStorage()._isSnapshot = newValue}
  }
  /// Returns true if `isSnapshot` has been explicitly set.
  public var hasIsSnapshot: Bool {return _storage._isSnapshot != nil}
  /// Clears the value of `isSnapshot`. Subsequent reads from it will return its default value.
  public mutating func clearIsSnapshot() {_uniqueStorage()._isSnapshot = nil}

  /// PB_OFFSET + MNM_TRADE_PRICE
  public var tradePrice: Double {
    get {return _storage._tradePrice ?? 0}
    set {_uniqueStorage()._tradePrice = newValue}
  }
  /// Returns true if `tradePrice` has been explicitly set.
  public var hasTradePrice: Bool {return _storage._tradePrice != nil}
  /// Clears the value of `tradePrice`. Subsequent reads from it will return its default value.
  public mutating func clearTradePrice() {_uniqueStorage()._tradePrice = nil}

  /// PB_OFFSET + MNM_TRADE_SIZE
  public var tradeSize: Int32 {
    get {return _storage._tradeSize ?? 0}
    set {_uniqueStorage()._tradeSize = newValue}
  }
  /// Returns true if `tradeSize` has been explicitly set.
  public var hasTradeSize: Bool {return _storage._tradeSize != nil}
  /// Clears the value of `tradeSize`. Subsequent reads from it will return its default value.
  public mutating func clearTradeSize() {_uniqueStorage()._tradeSize = nil}

  /// PB_OFFSET + MNM_TRANSACTION_TYPE
  public var aggressor: RtiLastTrade.TransactionType {
    get {return _storage._aggressor ?? .buy}
    set {_uniqueStorage()._aggressor = newValue}
  }
  /// Returns true if `aggressor` has been explicitly set.
  public var hasAggressor: Bool {return _storage._aggressor != nil}
  /// Clears the value of `aggressor`. Subsequent reads from it will return its default value.
  public mutating func clearAggressor() {_uniqueStorage()._aggressor = nil}

  /// PB_OFFSET + MNM_EXCH_ORD_ID
  public var exchangeOrderID: String {
    get {return _storage._exchangeOrderID ?? String()}
    set {_uniqueStorage()._exchangeOrderID = newValue}
  }
  /// Returns true if `exchangeOrderID` has been explicitly set.
  public var hasExchangeOrderID: Bool {return _storage._exchangeOrderID != nil}
  /// Clears the value of `exchangeOrderID`. Subsequent reads from it will return its default value.
  public mutating func clearExchangeOrderID() {_uniqueStorage()._exchangeOrderID = nil}

  /// PB_OFFSET + MNM_AGGRESSOR_EXCH_ORD_ID
  public var aggressorExchangeOrderID: String {
    get {return _storage._aggressorExchangeOrderID ?? String()}
    set {_uniqueStorage()._aggressorExchangeOrderID = newValue}
  }
  /// Returns true if `aggressorExchangeOrderID` has been explicitly set.
  public var hasAggressorExchangeOrderID: Bool {return _storage._aggressorExchangeOrderID != nil}
  /// Clears the value of `aggressorExchangeOrderID`. Subsequent reads from it will return its default value.
  public mutating func clearAggressorExchangeOrderID() {_uniqueStorage()._aggressorExchangeOrderID = nil}

  /// PB_OFFSET + MNM_NET_CHANGE
  public var netChange: Double {
    get {return _storage._netChange ?? 0}
    set {_uniqueStorage()._netChange = newValue}
  }
  /// Returns true if `netChange` has been explicitly set.
  public var hasNetChange: Bool {return _storage._netChange != nil}
  /// Clears the value of `netChange`. Subsequent reads from it will return its default value.
  public mutating func clearNetChange() {_uniqueStorage()._netChange = nil}

  /// PB_OFFSET + MNM_PERCENT_CHANGE
  public var percentChange: Double {
    get {return _storage._percentChange ?? 0}
    set {_uniqueStorage()._percentChange = newValue}
  }
  /// Returns true if `percentChange` has been explicitly set.
  public var hasPercentChange: Bool {return _storage._percentChange != nil}
  /// Clears the value of `percentChange`. Subsequent reads from it will return its default value.
  public mutating func clearPercentChange() {_uniqueStorage()._percentChange = nil}

  /// PB_OFFSET + MNM_TRADE_VOLUME
  public var volume: UInt64 {
    get {return _storage._volume ?? 0}
    set {_uniqueStorage()._volume = newValue}
  }
  /// Returns true if `volume` has been explicitly set.
  public var hasVolume: Bool {return _storage._volume != nil}
  /// Clears the value of `volume`. Subsequent reads from it will return its default value.
  public mutating func clearVolume() {_uniqueStorage()._volume = nil}

  /// PB_OFFSET + MNM_VWAP	
  public var vwap: Double {
    get {return _storage._vwap ?? 0}
    set {_uniqueStorage()._vwap = newValue}
  }
  /// Returns true if `vwap` has been explicitly set.
  public var hasVwap: Bool {return _storage._vwap != nil}
  /// Clears the value of `vwap`. Subsequent reads from it will return its default value.
  public mutating func clearVwap() {_uniqueStorage()._vwap = nil}

  /// PB_OFFSET + MNM_SECONDS_SINCE_BOE
  public var ssboe: Int32 {
    get {return _storage._ssboe ?? 0}
    set {_uniqueStorage()._ssboe = newValue}
  }
  /// Returns true if `ssboe` has been explicitly set.
  public var hasSsboe: Bool {return _storage._ssboe != nil}
  /// Clears the value of `ssboe`. Subsequent reads from it will return its default value.
  public mutating func clearSsboe() {_uniqueStorage()._ssboe = nil}

  /// PB_OFFSET + MNM_USECS
  public var usecs: Int32 {
    get {return _storage._usecs ?? 0}
    set {_uniqueStorage()._usecs = newValue}
  }
  /// Returns true if `usecs` has been explicitly set.
  public var hasUsecs: Bool {return _storage._usecs != nil}
  /// Clears the value of `usecs`. Subsequent reads from it will return its default value.
  public mutating func clearUsecs() {_uniqueStorage()._usecs = nil}

  /// PB_OFFSET + MNM_SOURCE_SSBOE
  public var sourceSsboe: Int32 {
    get {return _storage._sourceSsboe ?? 0}
    set {_uniqueStorage()._sourceSsboe = newValue}
  }
  /// Returns true if `sourceSsboe` has been explicitly set.
  public var hasSourceSsboe: Bool {return _storage._sourceSsboe != nil}
  /// Clears the value of `sourceSsboe`. Subsequent reads from it will return its default value.
  public mutating func clearSourceSsboe() {_uniqueStorage()._sourceSsboe = nil}

  /// PB_OFFSET + MNM_SOURCE_USECS
  public var sourceUsecs: Int32 {
    get {return _storage._sourceUsecs ?? 0}
    set {_uniqueStorage()._sourceUsecs = newValue}
  }
  /// Returns true if `sourceUsecs` has been explicitly set.
  public var hasSourceUsecs: Bool {return _storage._sourceUsecs != nil}
  /// Clears the value of `sourceUsecs`. Subsequent reads from it will return its default value.
  public mutating func clearSourceUsecs() {_uniqueStorage()._sourceUsecs = nil}

  /// PB_OFFSET + MNM_SOURCE_NSECS
  public var sourceNsecs: Int32 {
    get {return _storage._sourceNsecs ?? 0}
    set {_uniqueStorage()._sourceNsecs = newValue}
  }
  /// Returns true if `sourceNsecs` has been explicitly set.
  public var hasSourceNsecs: Bool {return _storage._sourceNsecs != nil}
  /// Clears the value of `sourceNsecs`. Subsequent reads from it will return its default value.
  public mutating func clearSourceNsecs() {_uniqueStorage()._sourceNsecs = nil}

  /// PB_OFFSET + MNM_JOP_SSBOE
  public var jopSsboe: Int32 {
    get {return _storage._jopSsboe ?? 0}
    set {_uniqueStorage()._jopSsboe = newValue}
  }
  /// Returns true if `jopSsboe` has been explicitly set.
  public var hasJopSsboe: Bool {return _storage._jopSsboe != nil}
  /// Clears the value of `jopSsboe`. Subsequent reads from it will return its default value.
  public mutating func clearJopSsboe() {_uniqueStorage()._jopSsboe = nil}

  /// PB_OFFSET + MNM_JOP_NSECS
  public var jopNsecs: Int32 {
    get {return _storage._jopNsecs ?? 0}
    set {_uniqueStorage()._jopNsecs = newValue}
  }
  /// Returns true if `jopNsecs` has been explicitly set.
  public var hasJopNsecs: Bool {return _storage._jopNsecs != nil}
  /// Clears the value of `jopNsecs`. Subsequent reads from it will return its default value.
  public mutating func clearJopNsecs() {_uniqueStorage()._jopNsecs = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// below enum is just for reference only, not used in this message
  public enum PresenceBits: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case lastTrade // = 1
    case netChange // = 2
    case precentChange // = 4
    case volume // = 8
    case vwap // = 16

    public init() {
      self = .lastTrade
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .lastTrade
      case 2: self = .netChange
      case 4: self = .precentChange
      case 8: self = .volume
      case 16: self = .vwap
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .lastTrade: return 1
      case .netChange: return 2
      case .precentChange: return 4
      case .volume: return 8
      case .vwap: return 16
      }
    }

  }

  public enum TransactionType: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case buy // = 1
    case sell // = 2

    public init() {
      self = .buy
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .buy
      case 2: self = .sell
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .buy: return 1
      case .sell: return 2
      }
    }

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

#if swift(>=4.2)

extension RtiLastTrade.PresenceBits: CaseIterable {
  // Support synthesized by the compiler.
}

extension RtiLastTrade.TransactionType: CaseIterable {
  // Support synthesized by the compiler.
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rti"

extension RtiLastTrade: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LastTrade"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    154467: .standard(proto: "template_id"),
    110100: .same(proto: "symbol"),
    110101: .same(proto: "exchange"),
    149138: .standard(proto: "presence_bits"),
    154571: .standard(proto: "clear_bits"),
    110121: .standard(proto: "is_snapshot"),
    100006: .standard(proto: "trade_price"),
    100178: .standard(proto: "trade_size"),
    112003: .same(proto: "aggressor"),
    149238: .standard(proto: "exchange_order_id"),
    154641: .standard(proto: "aggressor_exchange_order_id"),
    100011: .standard(proto: "net_change"),
    100056: .standard(proto: "percent_change"),
    100032: .same(proto: "volume"),
    101379: .same(proto: "vwap"),
    150100: .same(proto: "ssboe"),
    150101: .same(proto: "usecs"),
    150400: .standard(proto: "source_ssboe"),
    150401: .standard(proto: "source_usecs"),
    150404: .standard(proto: "source_nsecs"),
    150600: .standard(proto: "jop_ssboe"),
    150604: .standard(proto: "jop_nsecs"),
  ]

  fileprivate class _StorageClass {
    var _templateID: Int32? = nil
    var _symbol: String? = nil
    var _exchange: String? = nil
    var _presenceBits: UInt32? = nil
    var _clearBits_p: UInt32? = nil
    var _isSnapshot: Bool? = nil
    var _tradePrice: Double? = nil
    var _tradeSize: Int32? = nil
    var _aggressor: RtiLastTrade.TransactionType? = nil
    var _exchangeOrderID: String? = nil
    var _aggressorExchangeOrderID: String? = nil
    var _netChange: Double? = nil
    var _percentChange: Double? = nil
    var _volume: UInt64? = nil
    var _vwap: Double? = nil
    var _ssboe: Int32? = nil
    var _usecs: Int32? = nil
    var _sourceSsboe: Int32? = nil
    var _sourceUsecs: Int32? = nil
    var _sourceNsecs: Int32? = nil
    var _jopSsboe: Int32? = nil
    var _jopNsecs: Int32? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _templateID = source._templateID
      _symbol = source._symbol
      _exchange = source._exchange
      _presenceBits = source._presenceBits
      _clearBits_p = source._clearBits_p
      _isSnapshot = source._isSnapshot
      _tradePrice = source._tradePrice
      _tradeSize = source._tradeSize
      _aggressor = source._aggressor
      _exchangeOrderID = source._exchangeOrderID
      _aggressorExchangeOrderID = source._aggressorExchangeOrderID
      _netChange = source._netChange
      _percentChange = source._percentChange
      _volume = source._volume
      _vwap = source._vwap
      _ssboe = source._ssboe
      _usecs = source._usecs
      _sourceSsboe = source._sourceSsboe
      _sourceUsecs = source._sourceUsecs
      _sourceNsecs = source._sourceNsecs
      _jopSsboe = source._jopSsboe
      _jopNsecs = source._jopNsecs
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._templateID == nil {return false}
      return true
    }
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 100006: try decoder.decodeSingularDoubleField(value: &_storage._tradePrice)
        case 100011: try decoder.decodeSingularDoubleField(value: &_storage._netChange)
        case 100032: try decoder.decodeSingularUInt64Field(value: &_storage._volume)
        case 100056: try decoder.decodeSingularDoubleField(value: &_storage._percentChange)
        case 100178: try decoder.decodeSingularInt32Field(value: &_storage._tradeSize)
        case 101379: try decoder.decodeSingularDoubleField(value: &_storage._vwap)
        case 110100: try decoder.decodeSingularStringField(value: &_storage._symbol)
        case 110101: try decoder.decodeSingularStringField(value: &_storage._exchange)
        case 110121: try decoder.decodeSingularBoolField(value: &_storage._isSnapshot)
        case 112003: try decoder.decodeSingularEnumField(value: &_storage._aggressor)
        case 149138: try decoder.decodeSingularUInt32Field(value: &_storage._presenceBits)
        case 149238: try decoder.decodeSingularStringField(value: &_storage._exchangeOrderID)
        case 150100: try decoder.decodeSingularInt32Field(value: &_storage._ssboe)
        case 150101: try decoder.decodeSingularInt32Field(value: &_storage._usecs)
        case 150400: try decoder.decodeSingularInt32Field(value: &_storage._sourceSsboe)
        case 150401: try decoder.decodeSingularInt32Field(value: &_storage._sourceUsecs)
        case 150404: try decoder.decodeSingularInt32Field(value: &_storage._sourceNsecs)
        case 150600: try decoder.decodeSingularInt32Field(value: &_storage._jopSsboe)
        case 150604: try decoder.decodeSingularInt32Field(value: &_storage._jopNsecs)
        case 154467: try decoder.decodeSingularInt32Field(value: &_storage._templateID)
        case 154571: try decoder.decodeSingularUInt32Field(value: &_storage._clearBits_p)
        case 154641: try decoder.decodeSingularStringField(value: &_storage._aggressorExchangeOrderID)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._tradePrice {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 100006)
      }
      if let v = _storage._netChange {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 100011)
      }
      if let v = _storage._volume {
        try visitor.visitSingularUInt64Field(value: v, fieldNumber: 100032)
      }
      if let v = _storage._percentChange {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 100056)
      }
      if let v = _storage._tradeSize {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 100178)
      }
      if let v = _storage._vwap {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 101379)
      }
      if let v = _storage._symbol {
        try visitor.visitSingularStringField(value: v, fieldNumber: 110100)
      }
      if let v = _storage._exchange {
        try visitor.visitSingularStringField(value: v, fieldNumber: 110101)
      }
      if let v = _storage._isSnapshot {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 110121)
      }
      if let v = _storage._aggressor {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 112003)
      }
      if let v = _storage._presenceBits {
        try visitor.visitSingularUInt32Field(value: v, fieldNumber: 149138)
      }
      if let v = _storage._exchangeOrderID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 149238)
      }
      if let v = _storage._ssboe {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150100)
      }
      if let v = _storage._usecs {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150101)
      }
      if let v = _storage._sourceSsboe {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150400)
      }
      if let v = _storage._sourceUsecs {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150401)
      }
      if let v = _storage._sourceNsecs {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150404)
      }
      if let v = _storage._jopSsboe {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150600)
      }
      if let v = _storage._jopNsecs {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 150604)
      }
      if let v = _storage._templateID {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 154467)
      }
      if let v = _storage._clearBits_p {
        try visitor.visitSingularUInt32Field(value: v, fieldNumber: 154571)
      }
      if let v = _storage._aggressorExchangeOrderID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 154641)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RtiLastTrade, rhs: RtiLastTrade) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._templateID != rhs_storage._templateID {return false}
        if _storage._symbol != rhs_storage._symbol {return false}
        if _storage._exchange != rhs_storage._exchange {return false}
        if _storage._presenceBits != rhs_storage._presenceBits {return false}
        if _storage._clearBits_p != rhs_storage._clearBits_p {return false}
        if _storage._isSnapshot != rhs_storage._isSnapshot {return false}
        if _storage._tradePrice != rhs_storage._tradePrice {return false}
        if _storage._tradeSize != rhs_storage._tradeSize {return false}
        if _storage._aggressor != rhs_storage._aggressor {return false}
        if _storage._exchangeOrderID != rhs_storage._exchangeOrderID {return false}
        if _storage._aggressorExchangeOrderID != rhs_storage._aggressorExchangeOrderID {return false}
        if _storage._netChange != rhs_storage._netChange {return false}
        if _storage._percentChange != rhs_storage._percentChange {return false}
        if _storage._volume != rhs_storage._volume {return false}
        if _storage._vwap != rhs_storage._vwap {return false}
        if _storage._ssboe != rhs_storage._ssboe {return false}
        if _storage._usecs != rhs_storage._usecs {return false}
        if _storage._sourceSsboe != rhs_storage._sourceSsboe {return false}
        if _storage._sourceUsecs != rhs_storage._sourceUsecs {return false}
        if _storage._sourceNsecs != rhs_storage._sourceNsecs {return false}
        if _storage._jopSsboe != rhs_storage._jopSsboe {return false}
        if _storage._jopNsecs != rhs_storage._jopNsecs {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RtiLastTrade.PresenceBits: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "LAST_TRADE"),
    2: .same(proto: "NET_CHANGE"),
    4: .same(proto: "PRECENT_CHANGE"),
    8: .same(proto: "VOLUME"),
    16: .same(proto: "VWAP"),
  ]
}

extension RtiLastTrade.TransactionType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "BUY"),
    2: .same(proto: "SELL"),
  ]
}
