// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: OrderBook.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// PB_OFFSET = 100000 , is the offset added for each MNM field id
public struct RtiOrderBook {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// PB_OFFSET + MNM_TEMPLATE_ID
  public var templateID: Int32 {
    get {return _templateID ?? 0}
    set {_templateID = newValue}
  }
  /// Returns true if `templateID` has been explicitly set.
  public var hasTemplateID: Bool {return self._templateID != nil}
  /// Clears the value of `templateID`. Subsequent reads from it will return its default value.
  public mutating func clearTemplateID() {self._templateID = nil}

  /// PB_OFFSET + MNM_SYMBOL
  public var symbol: String {
    get {return _symbol ?? String()}
    set {_symbol = newValue}
  }
  /// Returns true if `symbol` has been explicitly set.
  public var hasSymbol: Bool {return self._symbol != nil}
  /// Clears the value of `symbol`. Subsequent reads from it will return its default value.
  public mutating func clearSymbol() {self._symbol = nil}

  /// PB_OFFSET + MNM_EXCHANGE
  public var exchange: String {
    get {return _exchange ?? String()}
    set {_exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {return self._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {self._exchange = nil}

  /// PB_OFFSET + MNM_PRICING_INDICATOR
  public var presenceBits: UInt32 {
    get {return _presenceBits ?? 0}
    set {_presenceBits = newValue}
  }
  /// Returns true if `presenceBits` has been explicitly set.
  public var hasPresenceBits: Bool {return self._presenceBits != nil}
  /// Clears the value of `presenceBits`. Subsequent reads from it will return its default value.
  public mutating func clearPresenceBits() {self._presenceBits = nil}

  /// PB_OFFSET + MNM_MARKET_DEPTH_UPDATE_TYPE
  public var updateType: RtiOrderBook.UpdateType {
    get {return _updateType ?? .clearOrderBook}
    set {_updateType = newValue}
  }
  /// Returns true if `updateType` has been explicitly set.
  public var hasUpdateType: Bool {return self._updateType != nil}
  /// Clears the value of `updateType`. Subsequent reads from it will return its default value.
  public mutating func clearUpdateType() {self._updateType = nil}

  /// PB_OFFSET + MNM_MARKET_DEPTH_BID_PRICE
  public var bidPrice: [Double] = []

  /// PB_OFFSET + MNM_MARKET_DEPTH_BID_SIZE
  public var bidSize: [Int32] = []

  /// PB_OFFSET + MNM_MARKET_DEPTH_BID_NO_OF_ORDERS
  public var bidOrders: [Int32] = []

  /// PB_OFFSET + MNM_MARKET_DEPTH_IMPLICIT_BID_SIZE
  public var implBidSize: [Int32] = []

  /// PB_OFFSET + MNM_MARKET_DEPTH_ASK_PRICE
  public var askPrice: [Double] = []

  /// PB_OFFSET + MNM_MARKET_DEPTH_ASK_SIZE
  public var askSize: [Int32] = []

  /// PB_OFFSET + MNM_MARKET_DEPTH_ASK_NO_OF_ORDERS
  public var askOrders: [Int32] = []

  /// PB_OFFSET + MNM_MARKET_DEPTH_IMPLICIT_ASK_SIZE
  public var implAskSize: [Int32] = []

  /// PB_OFFSET + MNM_SECONDS_SINCE_BOE
  public var ssboe: Int32 {
    get {return _ssboe ?? 0}
    set {_ssboe = newValue}
  }
  /// Returns true if `ssboe` has been explicitly set.
  public var hasSsboe: Bool {return self._ssboe != nil}
  /// Clears the value of `ssboe`. Subsequent reads from it will return its default value.
  public mutating func clearSsboe() {self._ssboe = nil}

  /// PB_OFFSET + MNM_USECS
  public var usecs: Int32 {
    get {return _usecs ?? 0}
    set {_usecs = newValue}
  }
  /// Returns true if `usecs` has been explicitly set.
  public var hasUsecs: Bool {return self._usecs != nil}
  /// Clears the value of `usecs`. Subsequent reads from it will return its default value.
  public mutating func clearUsecs() {self._usecs = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// below enum is just for reference only, not used in this message
  public enum PresenceBits: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case bid // = 1
    case ask // = 2

    public init() {
      self = .bid
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .bid
      case 2: self = .ask
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .bid: return 1
      case .ask: return 2
      }
    }

  }

  public enum UpdateType: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case clearOrderBook // = 1
    case noBook // = 2
    case snapshotImage // = 3
    case begin // = 4
    case middle // = 5
    case end // = 6
    case solo // = 7

    public init() {
      self = .clearOrderBook
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .clearOrderBook
      case 2: self = .noBook
      case 3: self = .snapshotImage
      case 4: self = .begin
      case 5: self = .middle
      case 6: self = .end
      case 7: self = .solo
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .clearOrderBook: return 1
      case .noBook: return 2
      case .snapshotImage: return 3
      case .begin: return 4
      case .middle: return 5
      case .end: return 6
      case .solo: return 7
      }
    }

  }

  public init() {}

  fileprivate var _templateID: Int32? = nil
  fileprivate var _symbol: String? = nil
  fileprivate var _exchange: String? = nil
  fileprivate var _presenceBits: UInt32? = nil
  fileprivate var _updateType: RtiOrderBook.UpdateType? = nil
  fileprivate var _ssboe: Int32? = nil
  fileprivate var _usecs: Int32? = nil
}

#if swift(>=4.2)

extension RtiOrderBook.PresenceBits: CaseIterable {
  // Support synthesized by the compiler.
}

extension RtiOrderBook.UpdateType: CaseIterable {
  // Support synthesized by the compiler.
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rti"

extension RtiOrderBook: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OrderBook"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    154467: .standard(proto: "template_id"),
    110100: .same(proto: "symbol"),
    110101: .same(proto: "exchange"),
    149138: .standard(proto: "presence_bits"),
    157608: .standard(proto: "update_type"),
    154282: .standard(proto: "bid_price"),
    154283: .standard(proto: "bid_size"),
    154401: .standard(proto: "bid_orders"),
    154412: .standard(proto: "impl_bid_size"),
    154284: .standard(proto: "ask_price"),
    154285: .standard(proto: "ask_size"),
    154402: .standard(proto: "ask_orders"),
    154415: .standard(proto: "impl_ask_size"),
    150100: .same(proto: "ssboe"),
    150101: .same(proto: "usecs"),
  ]

  public var isInitialized: Bool {
    if self._templateID == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 110100: try decoder.decodeSingularStringField(value: &self._symbol)
      case 110101: try decoder.decodeSingularStringField(value: &self._exchange)
      case 149138: try decoder.decodeSingularUInt32Field(value: &self._presenceBits)
      case 150100: try decoder.decodeSingularInt32Field(value: &self._ssboe)
      case 150101: try decoder.decodeSingularInt32Field(value: &self._usecs)
      case 154282: try decoder.decodeRepeatedDoubleField(value: &self.bidPrice)
      case 154283: try decoder.decodeRepeatedInt32Field(value: &self.bidSize)
      case 154284: try decoder.decodeRepeatedDoubleField(value: &self.askPrice)
      case 154285: try decoder.decodeRepeatedInt32Field(value: &self.askSize)
      case 154401: try decoder.decodeRepeatedInt32Field(value: &self.bidOrders)
      case 154402: try decoder.decodeRepeatedInt32Field(value: &self.askOrders)
      case 154412: try decoder.decodeRepeatedInt32Field(value: &self.implBidSize)
      case 154415: try decoder.decodeRepeatedInt32Field(value: &self.implAskSize)
      case 154467: try decoder.decodeSingularInt32Field(value: &self._templateID)
      case 157608: try decoder.decodeSingularEnumField(value: &self._updateType)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._symbol {
      try visitor.visitSingularStringField(value: v, fieldNumber: 110100)
    }
    if let v = self._exchange {
      try visitor.visitSingularStringField(value: v, fieldNumber: 110101)
    }
    if let v = self._presenceBits {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 149138)
    }
    if let v = self._ssboe {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 150100)
    }
    if let v = self._usecs {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 150101)
    }
    if !self.bidPrice.isEmpty {
      try visitor.visitRepeatedDoubleField(value: self.bidPrice, fieldNumber: 154282)
    }
    if !self.bidSize.isEmpty {
      try visitor.visitRepeatedInt32Field(value: self.bidSize, fieldNumber: 154283)
    }
    if !self.askPrice.isEmpty {
      try visitor.visitRepeatedDoubleField(value: self.askPrice, fieldNumber: 154284)
    }
    if !self.askSize.isEmpty {
      try visitor.visitRepeatedInt32Field(value: self.askSize, fieldNumber: 154285)
    }
    if !self.bidOrders.isEmpty {
      try visitor.visitRepeatedInt32Field(value: self.bidOrders, fieldNumber: 154401)
    }
    if !self.askOrders.isEmpty {
      try visitor.visitRepeatedInt32Field(value: self.askOrders, fieldNumber: 154402)
    }
    if !self.implBidSize.isEmpty {
      try visitor.visitRepeatedInt32Field(value: self.implBidSize, fieldNumber: 154412)
    }
    if !self.implAskSize.isEmpty {
      try visitor.visitRepeatedInt32Field(value: self.implAskSize, fieldNumber: 154415)
    }
    if let v = self._templateID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 154467)
    }
    if let v = self._updateType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 157608)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RtiOrderBook, rhs: RtiOrderBook) -> Bool {
    if lhs._templateID != rhs._templateID {return false}
    if lhs._symbol != rhs._symbol {return false}
    if lhs._exchange != rhs._exchange {return false}
    if lhs._presenceBits != rhs._presenceBits {return false}
    if lhs._updateType != rhs._updateType {return false}
    if lhs.bidPrice != rhs.bidPrice {return false}
    if lhs.bidSize != rhs.bidSize {return false}
    if lhs.bidOrders != rhs.bidOrders {return false}
    if lhs.implBidSize != rhs.implBidSize {return false}
    if lhs.askPrice != rhs.askPrice {return false}
    if lhs.askSize != rhs.askSize {return false}
    if lhs.askOrders != rhs.askOrders {return false}
    if lhs.implAskSize != rhs.implAskSize {return false}
    if lhs._ssboe != rhs._ssboe {return false}
    if lhs._usecs != rhs._usecs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RtiOrderBook.PresenceBits: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "BID"),
    2: .same(proto: "ASK"),
  ]
}

extension RtiOrderBook.UpdateType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "CLEAR_ORDER_BOOK"),
    2: .same(proto: "NO_BOOK"),
    3: .same(proto: "SNAPSHOT_IMAGE"),
    4: .same(proto: "BEGIN"),
    5: .same(proto: "MIDDLE"),
    6: .same(proto: "END"),
    7: .same(proto: "SOLO"),
  ]
}
