// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: RequestSearchSymbols.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// PB_OFFSET = 100000, is the offset added for each MNM field id
public struct RtiRequestSearchSymbols {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// PB_OFFSET + MNM_TEMPLATE_ID
  public var templateID: Int32 {
    get {return _templateID ?? 0}
    set {_templateID = newValue}
  }
  /// Returns true if `templateID` has been explicitly set.
  public var hasTemplateID: Bool {return self._templateID != nil}
  /// Clears the value of `templateID`. Subsequent reads from it will return its default value.
  public mutating func clearTemplateID() {self._templateID = nil}

  /// PB_OFFSET + MNM_USER_MSG
  public var userMsg: [String] = []

  /// PB_OFFSET + MNM_TEXT
  public var searchText: String {
    get {return _searchText ?? String()}
    set {_searchText = newValue}
  }
  /// Returns true if `searchText` has been explicitly set.
  public var hasSearchText: Bool {return self._searchText != nil}
  /// Clears the value of `searchText`. Subsequent reads from it will return its default value.
  public mutating func clearSearchText() {self._searchText = nil}

  /// PB_OFFSET + MNM_EXCHANGE
  public var exchange: String {
    get {return _exchange ?? String()}
    set {_exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {return self._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {self._exchange = nil}

  /// PB_OFFSET + MNM_PRODUCT_CODE
  public var productCode: String {
    get {return _productCode ?? String()}
    set {_productCode = newValue}
  }
  /// Returns true if `productCode` has been explicitly set.
  public var hasProductCode: Bool {return self._productCode != nil}
  /// Clears the value of `productCode`. Subsequent reads from it will return its default value.
  public mutating func clearProductCode() {self._productCode = nil}

  /// PB_OFFSET + MNM_INSTRUMENT_TYPE
  public var instrumentType: RtiRequestSearchSymbols.InstrumentType {
    get {return _instrumentType ?? .future}
    set {_instrumentType = newValue}
  }
  /// Returns true if `instrumentType` has been explicitly set.
  public var hasInstrumentType: Bool {return self._instrumentType != nil}
  /// Clears the value of `instrumentType`. Subsequent reads from it will return its default value.
  public mutating func clearInstrumentType() {self._instrumentType = nil}

  /// PB_OFFSET + MNM_SEARCH_PATTERN
  public var pattern: RtiRequestSearchSymbols.Pattern {
    get {return _pattern ?? .equals}
    set {_pattern = newValue}
  }
  /// Returns true if `pattern` has been explicitly set.
  public var hasPattern: Bool {return self._pattern != nil}
  /// Clears the value of `pattern`. Subsequent reads from it will return its default value.
  public mutating func clearPattern() {self._pattern = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Pattern: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case equals // = 1
    case contains // = 2

    public init() {
      self = .equals
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .equals
      case 2: self = .contains
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .equals: return 1
      case .contains: return 2
      }
    }

  }

  public enum InstrumentType: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case future // = 1
    case futureOption // = 2
    case futureStrategy // = 3
    case equity // = 4
    case equityOption // = 5
    case equityStrategy // = 6
    case index // = 7
    case indexOption // = 8
    case spread // = 9
    case synthetic // = 10

    public init() {
      self = .future
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .future
      case 2: self = .futureOption
      case 3: self = .futureStrategy
      case 4: self = .equity
      case 5: self = .equityOption
      case 6: self = .equityStrategy
      case 7: self = .index
      case 8: self = .indexOption
      case 9: self = .spread
      case 10: self = .synthetic
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .future: return 1
      case .futureOption: return 2
      case .futureStrategy: return 3
      case .equity: return 4
      case .equityOption: return 5
      case .equityStrategy: return 6
      case .index: return 7
      case .indexOption: return 8
      case .spread: return 9
      case .synthetic: return 10
      }
    }

  }

  public init() {}

  fileprivate var _templateID: Int32? = nil
  fileprivate var _searchText: String? = nil
  fileprivate var _exchange: String? = nil
  fileprivate var _productCode: String? = nil
  fileprivate var _instrumentType: RtiRequestSearchSymbols.InstrumentType? = nil
  fileprivate var _pattern: RtiRequestSearchSymbols.Pattern? = nil
}

#if swift(>=4.2)

extension RtiRequestSearchSymbols.Pattern: CaseIterable {
  // Support synthesized by the compiler.
}

extension RtiRequestSearchSymbols.InstrumentType: CaseIterable {
  // Support synthesized by the compiler.
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rti"

extension RtiRequestSearchSymbols: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestSearchSymbols"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    154467: .standard(proto: "template_id"),
    132760: .standard(proto: "user_msg"),
    120008: .standard(proto: "search_text"),
    110101: .same(proto: "exchange"),
    100749: .standard(proto: "product_code"),
    110116: .standard(proto: "instrument_type"),
    155008: .same(proto: "pattern"),
  ]

  public var isInitialized: Bool {
    if self._templateID == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 100749: try decoder.decodeSingularStringField(value: &self._productCode)
      case 110101: try decoder.decodeSingularStringField(value: &self._exchange)
      case 110116: try decoder.decodeSingularEnumField(value: &self._instrumentType)
      case 120008: try decoder.decodeSingularStringField(value: &self._searchText)
      case 132760: try decoder.decodeRepeatedStringField(value: &self.userMsg)
      case 154467: try decoder.decodeSingularInt32Field(value: &self._templateID)
      case 155008: try decoder.decodeSingularEnumField(value: &self._pattern)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._productCode {
      try visitor.visitSingularStringField(value: v, fieldNumber: 100749)
    }
    if let v = self._exchange {
      try visitor.visitSingularStringField(value: v, fieldNumber: 110101)
    }
    if let v = self._instrumentType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 110116)
    }
    if let v = self._searchText {
      try visitor.visitSingularStringField(value: v, fieldNumber: 120008)
    }
    if !self.userMsg.isEmpty {
      try visitor.visitRepeatedStringField(value: self.userMsg, fieldNumber: 132760)
    }
    if let v = self._templateID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 154467)
    }
    if let v = self._pattern {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 155008)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RtiRequestSearchSymbols, rhs: RtiRequestSearchSymbols) -> Bool {
    if lhs._templateID != rhs._templateID {return false}
    if lhs.userMsg != rhs.userMsg {return false}
    if lhs._searchText != rhs._searchText {return false}
    if lhs._exchange != rhs._exchange {return false}
    if lhs._productCode != rhs._productCode {return false}
    if lhs._instrumentType != rhs._instrumentType {return false}
    if lhs._pattern != rhs._pattern {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RtiRequestSearchSymbols.Pattern: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "EQUALS"),
    2: .same(proto: "CONTAINS"),
  ]
}

extension RtiRequestSearchSymbols.InstrumentType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "FUTURE"),
    2: .same(proto: "FUTURE_OPTION"),
    3: .same(proto: "FUTURE_STRATEGY"),
    4: .same(proto: "EQUITY"),
    5: .same(proto: "EQUITY_OPTION"),
    6: .same(proto: "EQUITY_STRATEGY"),
    7: .same(proto: "INDEX"),
    8: .same(proto: "INDEX_OPTION"),
    9: .same(proto: "SPREAD"),
    10: .same(proto: "SYNTHETIC"),
  ]
}
