// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: RequestMarketDataUpdate.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// update bits and Request enum defined here is also referred in request_subscribe_by_underlying.proto
/// make sure both these proto files are always same.
public struct RtiRequestMarketDataUpdate {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// PB_OFFSET + MNM_TEMPLATE_ID
  public var templateID: Int32 {
    get {return _templateID ?? 0}
    set {_templateID = newValue}
  }
  /// Returns true if `templateID` has been explicitly set.
  public var hasTemplateID: Bool {return self._templateID != nil}
  /// Clears the value of `templateID`. Subsequent reads from it will return its default value.
  public mutating func clearTemplateID() {self._templateID = nil}

  /// PB_OFFSET + MNM_USER_MSG
  public var userMsg: [String] = []

  /// PB_OFFSET + MNM_SYMBOL
  public var symbol: String {
    get {return _symbol ?? String()}
    set {_symbol = newValue}
  }
  /// Returns true if `symbol` has been explicitly set.
  public var hasSymbol: Bool {return self._symbol != nil}
  /// Clears the value of `symbol`. Subsequent reads from it will return its default value.
  public mutating func clearSymbol() {self._symbol = nil}

  /// PB_OFFSET + MNM_EXCHANGE
  public var exchange: String {
    get {return _exchange ?? String()}
    set {_exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {return self._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {self._exchange = nil}

  /// PB_OFFSET + MNM_REQUEST
  public var request: RtiRequestMarketDataUpdate.Request {
    get {return _request ?? .subscribe}
    set {_request = newValue}
  }
  /// Returns true if `request` has been explicitly set.
  public var hasRequest: Bool {return self._request != nil}
  /// Clears the value of `request`. Subsequent reads from it will return its default value.
  public mutating func clearRequest() {self._request = nil}

  /// PB_OFFSET + MNM_MESSAGE_ID
  public var updateBits: UInt32 {
    get {return _updateBits ?? 0}
    set {_updateBits = newValue}
  }
  /// Returns true if `updateBits` has been explicitly set.
  public var hasUpdateBits: Bool {return self._updateBits != nil}
  /// Clears the value of `updateBits`. Subsequent reads from it will return its default value.
  public mutating func clearUpdateBits() {self._updateBits = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// bit constants are defined using enum
  public enum UpdateBits: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case lastTrade // = 1
    case bbo // = 2
    case orderBook // = 4
    case `open` // = 8
    case openingIndicator // = 16
    case highLow // = 32
    case highBidLowAsk // = 64
    case close // = 128
    case closingIndicator // = 256
    case settlement // = 512
    case marketMode // = 1024
    case openInterest // = 2048
    case marginRate // = 4096
    case highPriceLimit // = 8192
    case lowPriceLimit // = 16384
    case projectedSettlement // = 32768

    public init() {
      self = .lastTrade
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .lastTrade
      case 2: self = .bbo
      case 4: self = .orderBook
      case 8: self = .open
      case 16: self = .openingIndicator
      case 32: self = .highLow
      case 64: self = .highBidLowAsk
      case 128: self = .close
      case 256: self = .closingIndicator
      case 512: self = .settlement
      case 1024: self = .marketMode
      case 2048: self = .openInterest
      case 4096: self = .marginRate
      case 8192: self = .highPriceLimit
      case 16384: self = .lowPriceLimit
      case 32768: self = .projectedSettlement
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .lastTrade: return 1
      case .bbo: return 2
      case .orderBook: return 4
      case .open: return 8
      case .openingIndicator: return 16
      case .highLow: return 32
      case .highBidLowAsk: return 64
      case .close: return 128
      case .closingIndicator: return 256
      case .settlement: return 512
      case .marketMode: return 1024
      case .openInterest: return 2048
      case .marginRate: return 4096
      case .highPriceLimit: return 8192
      case .lowPriceLimit: return 16384
      case .projectedSettlement: return 32768
      }
    }

  }

  public enum Request: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case subscribe // = 1
    case unsubscribe // = 2

    public init() {
      self = .subscribe
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .subscribe
      case 2: self = .unsubscribe
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .subscribe: return 1
      case .unsubscribe: return 2
      }
    }

  }

  public init() {}

  fileprivate var _templateID: Int32? = nil
  fileprivate var _symbol: String? = nil
  fileprivate var _exchange: String? = nil
  fileprivate var _request: RtiRequestMarketDataUpdate.Request? = nil
  fileprivate var _updateBits: UInt32? = nil
}

#if swift(>=4.2)

extension RtiRequestMarketDataUpdate.UpdateBits: CaseIterable {
  // Support synthesized by the compiler.
}

extension RtiRequestMarketDataUpdate.Request: CaseIterable {
  // Support synthesized by the compiler.
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rti"

extension RtiRequestMarketDataUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestMarketDataUpdate"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    154467: .standard(proto: "template_id"),
    132760: .standard(proto: "user_msg"),
    110100: .same(proto: "symbol"),
    110101: .same(proto: "exchange"),
    100000: .same(proto: "request"),
    154211: .standard(proto: "update_bits"),
  ]

  public var isInitialized: Bool {
    if self._templateID == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 100000: try decoder.decodeSingularEnumField(value: &self._request)
      case 110100: try decoder.decodeSingularStringField(value: &self._symbol)
      case 110101: try decoder.decodeSingularStringField(value: &self._exchange)
      case 132760: try decoder.decodeRepeatedStringField(value: &self.userMsg)
      case 154211: try decoder.decodeSingularUInt32Field(value: &self._updateBits)
      case 154467: try decoder.decodeSingularInt32Field(value: &self._templateID)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._request {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 100000)
    }
    if let v = self._symbol {
      try visitor.visitSingularStringField(value: v, fieldNumber: 110100)
    }
    if let v = self._exchange {
      try visitor.visitSingularStringField(value: v, fieldNumber: 110101)
    }
    if !self.userMsg.isEmpty {
      try visitor.visitRepeatedStringField(value: self.userMsg, fieldNumber: 132760)
    }
    if let v = self._updateBits {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 154211)
    }
    if let v = self._templateID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 154467)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RtiRequestMarketDataUpdate, rhs: RtiRequestMarketDataUpdate) -> Bool {
    if lhs._templateID != rhs._templateID {return false}
    if lhs.userMsg != rhs.userMsg {return false}
    if lhs._symbol != rhs._symbol {return false}
    if lhs._exchange != rhs._exchange {return false}
    if lhs._request != rhs._request {return false}
    if lhs._updateBits != rhs._updateBits {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RtiRequestMarketDataUpdate.UpdateBits: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "LAST_TRADE"),
    2: .same(proto: "BBO"),
    4: .same(proto: "ORDER_BOOK"),
    8: .same(proto: "OPEN"),
    16: .same(proto: "OPENING_INDICATOR"),
    32: .same(proto: "HIGH_LOW"),
    64: .same(proto: "HIGH_BID_LOW_ASK"),
    128: .same(proto: "CLOSE"),
    256: .same(proto: "CLOSING_INDICATOR"),
    512: .same(proto: "SETTLEMENT"),
    1024: .same(proto: "MARKET_MODE"),
    2048: .same(proto: "OPEN_INTEREST"),
    4096: .same(proto: "MARGIN_RATE"),
    8192: .same(proto: "HIGH_PRICE_LIMIT"),
    16384: .same(proto: "LOW_PRICE_LIMIT"),
    32768: .same(proto: "PROJECTED_SETTLEMENT"),
  ]
}

extension RtiRequestMarketDataUpdate.Request: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "SUBSCRIBE"),
    2: .same(proto: "UNSUBSCRIBE"),
  ]
}
