// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: RequestDepthByOrderUpdates.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// PB_OFFSET = 100000, is the offset added for each MNM field id
public struct RtiRequestDepthByOrderUpdates {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// PB_OFFSET + MNM_TEMPLATE_ID
  public var templateID: Int32 {
    get {return _templateID ?? 0}
    set {_templateID = newValue}
  }
  /// Returns true if `templateID` has been explicitly set.
  public var hasTemplateID: Bool {return self._templateID != nil}
  /// Clears the value of `templateID`. Subsequent reads from it will return its default value.
  public mutating func clearTemplateID() {self._templateID = nil}

  /// PB_OFFSET + MNM_USER_MSG
  public var userMsg: [String] = []

  /// PB_OFFSET + MNM_REQUEST
  public var request: RtiRequestDepthByOrderUpdates.Request {
    get {return _request ?? .subscribe}
    set {_request = newValue}
  }
  /// Returns true if `request` has been explicitly set.
  public var hasRequest: Bool {return self._request != nil}
  /// Clears the value of `request`. Subsequent reads from it will return its default value.
  public mutating func clearRequest() {self._request = nil}

  /// PB_OFFSET + MNM_SYMBOL
  public var symbol: String {
    get {return _symbol ?? String()}
    set {_symbol = newValue}
  }
  /// Returns true if `symbol` has been explicitly set.
  public var hasSymbol: Bool {return self._symbol != nil}
  /// Clears the value of `symbol`. Subsequent reads from it will return its default value.
  public mutating func clearSymbol() {self._symbol = nil}

  /// PB_OFFSET + MNM_EXCHANGE
  public var exchange: String {
    get {return _exchange ?? String()}
    set {_exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {return self._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {self._exchange = nil}

  /// PB_OFFSET + MNM_MARKET_DEPTH_PRICE
  public var depthPrice: Double {
    get {return _depthPrice ?? 0}
    set {_depthPrice = newValue}
  }
  /// Returns true if `depthPrice` has been explicitly set.
  public var hasDepthPrice: Bool {return self._depthPrice != nil}
  /// Clears the value of `depthPrice`. Subsequent reads from it will return its default value.
  public mutating func clearDepthPrice() {self._depthPrice = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Request: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case subscribe // = 1
    case unsubscribe // = 2

    public init() {
      self = .subscribe
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .subscribe
      case 2: self = .unsubscribe
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .subscribe: return 1
      case .unsubscribe: return 2
      }
    }

  }

  public init() {}

  fileprivate var _templateID: Int32? = nil
  fileprivate var _request: RtiRequestDepthByOrderUpdates.Request? = nil
  fileprivate var _symbol: String? = nil
  fileprivate var _exchange: String? = nil
  fileprivate var _depthPrice: Double? = nil
}

#if swift(>=4.2)

extension RtiRequestDepthByOrderUpdates.Request: CaseIterable {
  // Support synthesized by the compiler.
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rti"

extension RtiRequestDepthByOrderUpdates: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestDepthByOrderUpdates"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    154467: .standard(proto: "template_id"),
    132760: .standard(proto: "user_msg"),
    100000: .same(proto: "request"),
    110100: .same(proto: "symbol"),
    110101: .same(proto: "exchange"),
    154405: .standard(proto: "depth_price"),
  ]

  public var isInitialized: Bool {
    if self._templateID == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 100000: try decoder.decodeSingularEnumField(value: &self._request)
      case 110100: try decoder.decodeSingularStringField(value: &self._symbol)
      case 110101: try decoder.decodeSingularStringField(value: &self._exchange)
      case 132760: try decoder.decodeRepeatedStringField(value: &self.userMsg)
      case 154405: try decoder.decodeSingularDoubleField(value: &self._depthPrice)
      case 154467: try decoder.decodeSingularInt32Field(value: &self._templateID)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._request {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 100000)
    }
    if let v = self._symbol {
      try visitor.visitSingularStringField(value: v, fieldNumber: 110100)
    }
    if let v = self._exchange {
      try visitor.visitSingularStringField(value: v, fieldNumber: 110101)
    }
    if !self.userMsg.isEmpty {
      try visitor.visitRepeatedStringField(value: self.userMsg, fieldNumber: 132760)
    }
    if let v = self._depthPrice {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 154405)
    }
    if let v = self._templateID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 154467)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RtiRequestDepthByOrderUpdates, rhs: RtiRequestDepthByOrderUpdates) -> Bool {
    if lhs._templateID != rhs._templateID {return false}
    if lhs.userMsg != rhs.userMsg {return false}
    if lhs._request != rhs._request {return false}
    if lhs._symbol != rhs._symbol {return false}
    if lhs._exchange != rhs._exchange {return false}
    if lhs._depthPrice != rhs._depthPrice {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RtiRequestDepthByOrderUpdates.Request: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "SUBSCRIBE"),
    2: .same(proto: "UNSUBSCRIBE"),
  ]
}
