// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ResponseSearchSymbols.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// PB_OFFSET = 100000, is the offset added for each MNM field id
public struct RtiResponseSearchSymbols {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// PB_OFFSET + MNM_TEMPLATE_ID
  public var templateID: Int32 {
    get {return _templateID ?? 0}
    set {_templateID = newValue}
  }
  /// Returns true if `templateID` has been explicitly set.
  public var hasTemplateID: Bool {return self._templateID != nil}
  /// Clears the value of `templateID`. Subsequent reads from it will return its default value.
  public mutating func clearTemplateID() {self._templateID = nil}

  /// PB_OFFSET + MNM_USER_MSG	
  public var userMsg: [String] = []

  /// PB_OFFSET + MNM_REQUEST_HANDLER_RESPONSE_CODE
  public var rqHandlerRpCode: [String] = []

  /// PB_OFFSET + MNM_RESPONSE_CODE
  public var rpCode: [String] = []

  /// PB_OFFSET + MNM_SYMBOL
  public var symbol: String {
    get {return _symbol ?? String()}
    set {_symbol = newValue}
  }
  /// Returns true if `symbol` has been explicitly set.
  public var hasSymbol: Bool {return self._symbol != nil}
  /// Clears the value of `symbol`. Subsequent reads from it will return its default value.
  public mutating func clearSymbol() {self._symbol = nil}

  /// PB_OFFSET + MNM_EXCHANGE
  public var exchange: String {
    get {return _exchange ?? String()}
    set {_exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {return self._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {self._exchange = nil}

  /// PB_OFFSET + MNM_SYMBOL_NAME	
  public var symbolName: String {
    get {return _symbolName ?? String()}
    set {_symbolName = newValue}
  }
  /// Returns true if `symbolName` has been explicitly set.
  public var hasSymbolName: Bool {return self._symbolName != nil}
  /// Clears the value of `symbolName`. Subsequent reads from it will return its default value.
  public mutating func clearSymbolName() {self._symbolName = nil}

  /// PB_OFFSET + MNM_PRODUCT_CODE
  public var productCode: String {
    get {return _productCode ?? String()}
    set {_productCode = newValue}
  }
  /// Returns true if `productCode` has been explicitly set.
  public var hasProductCode: Bool {return self._productCode != nil}
  /// Clears the value of `productCode`. Subsequent reads from it will return its default value.
  public mutating func clearProductCode() {self._productCode = nil}

  /// PB_OFFSET + MNM_INSTRUMENT_TYPE
  public var instrumentType: String {
    get {return _instrumentType ?? String()}
    set {_instrumentType = newValue}
  }
  /// Returns true if `instrumentType` has been explicitly set.
  public var hasInstrumentType: Bool {return self._instrumentType != nil}
  /// Clears the value of `instrumentType`. Subsequent reads from it will return its default value.
  public mutating func clearInstrumentType() {self._instrumentType = nil}

  /// PB_OFFSET + MNM_EXPIRATION_DATE
  public var expirationDate: String {
    get {return _expirationDate ?? String()}
    set {_expirationDate = newValue}
  }
  /// Returns true if `expirationDate` has been explicitly set.
  public var hasExpirationDate: Bool {return self._expirationDate != nil}
  /// Clears the value of `expirationDate`. Subsequent reads from it will return its default value.
  public mutating func clearExpirationDate() {self._expirationDate = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _templateID: Int32? = nil
  fileprivate var _symbol: String? = nil
  fileprivate var _exchange: String? = nil
  fileprivate var _symbolName: String? = nil
  fileprivate var _productCode: String? = nil
  fileprivate var _instrumentType: String? = nil
  fileprivate var _expirationDate: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rti"

extension RtiResponseSearchSymbols: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ResponseSearchSymbols"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    154467: .standard(proto: "template_id"),
    132760: .standard(proto: "user_msg"),
    132764: .standard(proto: "rq_handler_rp_code"),
    132766: .standard(proto: "rp_code"),
    110100: .same(proto: "symbol"),
    110101: .same(proto: "exchange"),
    100003: .standard(proto: "symbol_name"),
    100749: .standard(proto: "product_code"),
    110116: .standard(proto: "instrument_type"),
    100067: .standard(proto: "expiration_date"),
  ]

  public var isInitialized: Bool {
    if self._templateID == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 100003: try decoder.decodeSingularStringField(value: &self._symbolName)
      case 100067: try decoder.decodeSingularStringField(value: &self._expirationDate)
      case 100749: try decoder.decodeSingularStringField(value: &self._productCode)
      case 110100: try decoder.decodeSingularStringField(value: &self._symbol)
      case 110101: try decoder.decodeSingularStringField(value: &self._exchange)
      case 110116: try decoder.decodeSingularStringField(value: &self._instrumentType)
      case 132760: try decoder.decodeRepeatedStringField(value: &self.userMsg)
      case 132764: try decoder.decodeRepeatedStringField(value: &self.rqHandlerRpCode)
      case 132766: try decoder.decodeRepeatedStringField(value: &self.rpCode)
      case 154467: try decoder.decodeSingularInt32Field(value: &self._templateID)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._symbolName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 100003)
    }
    if let v = self._expirationDate {
      try visitor.visitSingularStringField(value: v, fieldNumber: 100067)
    }
    if let v = self._productCode {
      try visitor.visitSingularStringField(value: v, fieldNumber: 100749)
    }
    if let v = self._symbol {
      try visitor.visitSingularStringField(value: v, fieldNumber: 110100)
    }
    if let v = self._exchange {
      try visitor.visitSingularStringField(value: v, fieldNumber: 110101)
    }
    if let v = self._instrumentType {
      try visitor.visitSingularStringField(value: v, fieldNumber: 110116)
    }
    if !self.userMsg.isEmpty {
      try visitor.visitRepeatedStringField(value: self.userMsg, fieldNumber: 132760)
    }
    if !self.rqHandlerRpCode.isEmpty {
      try visitor.visitRepeatedStringField(value: self.rqHandlerRpCode, fieldNumber: 132764)
    }
    if !self.rpCode.isEmpty {
      try visitor.visitRepeatedStringField(value: self.rpCode, fieldNumber: 132766)
    }
    if let v = self._templateID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 154467)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RtiResponseSearchSymbols, rhs: RtiResponseSearchSymbols) -> Bool {
    if lhs._templateID != rhs._templateID {return false}
    if lhs.userMsg != rhs.userMsg {return false}
    if lhs.rqHandlerRpCode != rhs.rqHandlerRpCode {return false}
    if lhs.rpCode != rhs.rpCode {return false}
    if lhs._symbol != rhs._symbol {return false}
    if lhs._exchange != rhs._exchange {return false}
    if lhs._symbolName != rhs._symbolName {return false}
    if lhs._productCode != rhs._productCode {return false}
    if lhs._instrumentType != rhs._instrumentType {return false}
    if lhs._expirationDate != rhs._expirationDate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
