// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: RequestLogin.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// PB_OFFSET = 100000 , is the offset added for each MNM field id
public struct RtiRequestLogin {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// PB_OFFSET + MNM_TEMPLATE_ID
  public var templateID: Int32 {
    get {return _templateID ?? 0}
    set {_templateID = newValue}
  }
  /// Returns true if `templateID` has been explicitly set.
  public var hasTemplateID: Bool {return self._templateID != nil}
  /// Clears the value of `templateID`. Subsequent reads from it will return its default value.
  public mutating func clearTemplateID() {self._templateID = nil}

  /// PB_OFFSET + MNM_TEMPLATE_VERSION
  public var templateVersion: String {
    get {return _templateVersion ?? String()}
    set {_templateVersion = newValue}
  }
  /// Returns true if `templateVersion` has been explicitly set.
  public var hasTemplateVersion: Bool {return self._templateVersion != nil}
  /// Clears the value of `templateVersion`. Subsequent reads from it will return its default value.
  public mutating func clearTemplateVersion() {self._templateVersion = nil}

  /// PB_OFFSET + MNM_USER_MSG
  public var userMsg: [String] = []

  /// PB_OFFSET + MNM_USER
  public var user: String {
    get {return _user ?? String()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  public var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  public mutating func clearUser() {self._user = nil}

  /// PB_OFFSET + MNM_PASSWORD
  public var password: String {
    get {return _password ?? String()}
    set {_password = newValue}
  }
  /// Returns true if `password` has been explicitly set.
  public var hasPassword: Bool {return self._password != nil}
  /// Clears the value of `password`. Subsequent reads from it will return its default value.
  public mutating func clearPassword() {self._password = nil}

  /// PB_OFFSET + MNM_APPLICATION_NAME
  public var appName: String {
    get {return _appName ?? String()}
    set {_appName = newValue}
  }
  /// Returns true if `appName` has been explicitly set.
  public var hasAppName: Bool {return self._appName != nil}
  /// Clears the value of `appName`. Subsequent reads from it will return its default value.
  public mutating func clearAppName() {self._appName = nil}

  /// PB_OFFSET + MNM_APP_VERSION
  public var appVersion: String {
    get {return _appVersion ?? String()}
    set {_appVersion = newValue}
  }
  /// Returns true if `appVersion` has been explicitly set.
  public var hasAppVersion: Bool {return self._appVersion != nil}
  /// Clears the value of `appVersion`. Subsequent reads from it will return its default value.
  public mutating func clearAppVersion() {self._appVersion = nil}

  /// PB_OFFSET + MNM_RITHMIC_SYSTEM_NAME
  public var systemName: String {
    get {return _systemName ?? String()}
    set {_systemName = newValue}
  }
  /// Returns true if `systemName` has been explicitly set.
  public var hasSystemName: Bool {return self._systemName != nil}
  /// Clears the value of `systemName`. Subsequent reads from it will return its default value.
  public mutating func clearSystemName() {self._systemName = nil}

  /// PB_OFFSET + MNM_RITHMIC_INFRASTRUCTURE_PLANT
  public var infraType: RtiRequestLogin.SysInfraType {
    get {return _infraType ?? .tickerPlant}
    set {_infraType = newValue}
  }
  /// Returns true if `infraType` has been explicitly set.
  public var hasInfraType: Bool {return self._infraType != nil}
  /// Clears the value of `infraType`. Subsequent reads from it will return its default value.
  public mutating func clearInfraType() {self._infraType = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum SysInfraType: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case tickerPlant // = 1
    case orderPlant // = 2
    case historyPlant // = 3
    case pnlPlant // = 4
    case repositoryPlant // = 5

    public init() {
      self = .tickerPlant
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 1: self = .tickerPlant
      case 2: self = .orderPlant
      case 3: self = .historyPlant
      case 4: self = .pnlPlant
      case 5: self = .repositoryPlant
      default: return nil
      }
    }

    public var rawValue: Int {
      switch self {
      case .tickerPlant: return 1
      case .orderPlant: return 2
      case .historyPlant: return 3
      case .pnlPlant: return 4
      case .repositoryPlant: return 5
      }
    }

  }

  public init() {}

  fileprivate var _templateID: Int32? = nil
  fileprivate var _templateVersion: String? = nil
  fileprivate var _user: String? = nil
  fileprivate var _password: String? = nil
  fileprivate var _appName: String? = nil
  fileprivate var _appVersion: String? = nil
  fileprivate var _systemName: String? = nil
  fileprivate var _infraType: RtiRequestLogin.SysInfraType? = nil
}

#if swift(>=4.2)

extension RtiRequestLogin.SysInfraType: CaseIterable {
  // Support synthesized by the compiler.
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rti"

extension RtiRequestLogin: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestLogin"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    154467: .standard(proto: "template_id"),
    153634: .standard(proto: "template_version"),
    132760: .standard(proto: "user_msg"),
    131003: .same(proto: "user"),
    130004: .same(proto: "password"),
    130002: .standard(proto: "app_name"),
    131803: .standard(proto: "app_version"),
    153628: .standard(proto: "system_name"),
    153621: .standard(proto: "infra_type"),
  ]

  public var isInitialized: Bool {
    if self._templateID == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 130002: try decoder.decodeSingularStringField(value: &self._appName)
      case 130004: try decoder.decodeSingularStringField(value: &self._password)
      case 131003: try decoder.decodeSingularStringField(value: &self._user)
      case 131803: try decoder.decodeSingularStringField(value: &self._appVersion)
      case 132760: try decoder.decodeRepeatedStringField(value: &self.userMsg)
      case 153621: try decoder.decodeSingularEnumField(value: &self._infraType)
      case 153628: try decoder.decodeSingularStringField(value: &self._systemName)
      case 153634: try decoder.decodeSingularStringField(value: &self._templateVersion)
      case 154467: try decoder.decodeSingularInt32Field(value: &self._templateID)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._appName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 130002)
    }
    if let v = self._password {
      try visitor.visitSingularStringField(value: v, fieldNumber: 130004)
    }
    if let v = self._user {
      try visitor.visitSingularStringField(value: v, fieldNumber: 131003)
    }
    if let v = self._appVersion {
      try visitor.visitSingularStringField(value: v, fieldNumber: 131803)
    }
    if !self.userMsg.isEmpty {
      try visitor.visitRepeatedStringField(value: self.userMsg, fieldNumber: 132760)
    }
    if let v = self._infraType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 153621)
    }
    if let v = self._systemName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 153628)
    }
    if let v = self._templateVersion {
      try visitor.visitSingularStringField(value: v, fieldNumber: 153634)
    }
    if let v = self._templateID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 154467)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RtiRequestLogin, rhs: RtiRequestLogin) -> Bool {
    if lhs._templateID != rhs._templateID {return false}
    if lhs._templateVersion != rhs._templateVersion {return false}
    if lhs.userMsg != rhs.userMsg {return false}
    if lhs._user != rhs._user {return false}
    if lhs._password != rhs._password {return false}
    if lhs._appName != rhs._appName {return false}
    if lhs._appVersion != rhs._appVersion {return false}
    if lhs._systemName != rhs._systemName {return false}
    if lhs._infraType != rhs._infraType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RtiRequestLogin.SysInfraType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "TICKER_PLANT"),
    2: .same(proto: "ORDER_PLANT"),
    3: .same(proto: "HISTORY_PLANT"),
    4: .same(proto: "PNL_PLANT"),
    5: .same(proto: "REPOSITORY_PLANT"),
  ]
}
