// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ResponseLogin.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// PB_OFFSET = 100000 , is the offset added for each MNM field id
public struct RtiResponseLogin {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// PB_OFFSET + MNM_TEMPLATE_ID
  public var templateID: Int32 {
    get {return _templateID ?? 0}
    set {_templateID = newValue}
  }
  /// Returns true if `templateID` has been explicitly set.
  public var hasTemplateID: Bool {return self._templateID != nil}
  /// Clears the value of `templateID`. Subsequent reads from it will return its default value.
  public mutating func clearTemplateID() {self._templateID = nil}

  /// PB_OFFSET + MNM_TEMPLATE_VERSION
  public var templateVersion: String {
    get {return _templateVersion ?? String()}
    set {_templateVersion = newValue}
  }
  /// Returns true if `templateVersion` has been explicitly set.
  public var hasTemplateVersion: Bool {return self._templateVersion != nil}
  /// Clears the value of `templateVersion`. Subsequent reads from it will return its default value.
  public mutating func clearTemplateVersion() {self._templateVersion = nil}

  /// PB_OFFSET + MNM_USER_MSG	
  public var userMsg: [String] = []

  /// PB_OFFSET + MNM_RESPONSE_CODE
  public var rpCode: [String] = []

  /// PB_OFFSET + MNM_FCM_ID
  public var fcmID: String {
    get {return _fcmID ?? String()}
    set {_fcmID = newValue}
  }
  /// Returns true if `fcmID` has been explicitly set.
  public var hasFcmID: Bool {return self._fcmID != nil}
  /// Clears the value of `fcmID`. Subsequent reads from it will return its default value.
  public mutating func clearFcmID() {self._fcmID = nil}

  /// PB_OFFSET + MNM_IB_ID
  public var ibID: String {
    get {return _ibID ?? String()}
    set {_ibID = newValue}
  }
  /// Returns true if `ibID` has been explicitly set.
  public var hasIbID: Bool {return self._ibID != nil}
  /// Clears the value of `ibID`. Subsequent reads from it will return its default value.
  public mutating func clearIbID() {self._ibID = nil}

  /// PB_OFFSET + MNM_COUNTRY_CODE
  public var countryCode: String {
    get {return _countryCode ?? String()}
    set {_countryCode = newValue}
  }
  /// Returns true if `countryCode` has been explicitly set.
  public var hasCountryCode: Bool {return self._countryCode != nil}
  /// Clears the value of `countryCode`. Subsequent reads from it will return its default value.
  public mutating func clearCountryCode() {self._countryCode = nil}

  /// PB_OFFSET + MNM_STATE_CODE
  public var stateCode: String {
    get {return _stateCode ?? String()}
    set {_stateCode = newValue}
  }
  /// Returns true if `stateCode` has been explicitly set.
  public var hasStateCode: Bool {return self._stateCode != nil}
  /// Clears the value of `stateCode`. Subsequent reads from it will return its default value.
  public mutating func clearStateCode() {self._stateCode = nil}

  /// PB_OFFSET + MNM_HEARTBEAT_INTERVAL
  public var heartbeatInterval: Double {
    get {return _heartbeatInterval ?? 0}
    set {_heartbeatInterval = newValue}
  }
  /// Returns true if `heartbeatInterval` has been explicitly set.
  public var hasHeartbeatInterval: Bool {return self._heartbeatInterval != nil}
  /// Clears the value of `heartbeatInterval`. Subsequent reads from it will return its default value.
  public mutating func clearHeartbeatInterval() {self._heartbeatInterval = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _templateID: Int32? = nil
  fileprivate var _templateVersion: String? = nil
  fileprivate var _fcmID: String? = nil
  fileprivate var _ibID: String? = nil
  fileprivate var _countryCode: String? = nil
  fileprivate var _stateCode: String? = nil
  fileprivate var _heartbeatInterval: Double? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rti"

extension RtiResponseLogin: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ResponseLogin"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    154467: .standard(proto: "template_id"),
    153634: .standard(proto: "template_version"),
    132760: .standard(proto: "user_msg"),
    132766: .standard(proto: "rp_code"),
    154013: .standard(proto: "fcm_id"),
    154014: .standard(proto: "ib_id"),
    154712: .standard(proto: "country_code"),
    154713: .standard(proto: "state_code"),
    153633: .standard(proto: "heartbeat_interval"),
  ]

  public var isInitialized: Bool {
    if self._templateID == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 132760: try decoder.decodeRepeatedStringField(value: &self.userMsg)
      case 132766: try decoder.decodeRepeatedStringField(value: &self.rpCode)
      case 153633: try decoder.decodeSingularDoubleField(value: &self._heartbeatInterval)
      case 153634: try decoder.decodeSingularStringField(value: &self._templateVersion)
      case 154013: try decoder.decodeSingularStringField(value: &self._fcmID)
      case 154014: try decoder.decodeSingularStringField(value: &self._ibID)
      case 154467: try decoder.decodeSingularInt32Field(value: &self._templateID)
      case 154712: try decoder.decodeSingularStringField(value: &self._countryCode)
      case 154713: try decoder.decodeSingularStringField(value: &self._stateCode)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.userMsg.isEmpty {
      try visitor.visitRepeatedStringField(value: self.userMsg, fieldNumber: 132760)
    }
    if !self.rpCode.isEmpty {
      try visitor.visitRepeatedStringField(value: self.rpCode, fieldNumber: 132766)
    }
    if let v = self._heartbeatInterval {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 153633)
    }
    if let v = self._templateVersion {
      try visitor.visitSingularStringField(value: v, fieldNumber: 153634)
    }
    if let v = self._fcmID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 154013)
    }
    if let v = self._ibID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 154014)
    }
    if let v = self._templateID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 154467)
    }
    if let v = self._countryCode {
      try visitor.visitSingularStringField(value: v, fieldNumber: 154712)
    }
    if let v = self._stateCode {
      try visitor.visitSingularStringField(value: v, fieldNumber: 154713)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RtiResponseLogin, rhs: RtiResponseLogin) -> Bool {
    if lhs._templateID != rhs._templateID {return false}
    if lhs._templateVersion != rhs._templateVersion {return false}
    if lhs.userMsg != rhs.userMsg {return false}
    if lhs.rpCode != rhs.rpCode {return false}
    if lhs._fcmID != rhs._fcmID {return false}
    if lhs._ibID != rhs._ibID {return false}
    if lhs._countryCode != rhs._countryCode {return false}
    if lhs._stateCode != rhs._stateCode {return false}
    if lhs._heartbeatInterval != rhs._heartbeatInterval {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
